name: 4-Test wheels using pipenv

on:
  #push:
  #  branches: [ main ]
  workflow_dispatch:

jobs:
  matrix:
    name: Generate matrix of samples
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      -
        uses: actions/checkout@v2
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
      -
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      -
        id: set-matrix
        run: |
          import json
          with open("ci/build-test.json") as fp:
              data = json.load(fp)
          #samples = json.dumps(list(data.keys()))
          samples = json.dumps(["bcrypt"])
          print(f"::set-output name=matrix::{samples}")
        shell: python

  tests:
    needs: [matrix]
    strategy:
      fail-fast: false
      matrix:
        sample: ${{ fromJSON(needs.matrix.outputs.matrix) }}
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
        architecture: [x64, x86]
        exclude:
          - os: ubuntu-latest
            architecture: x86
          - os: macos-latest
            architecture: x86
          - os: ubuntu-latest
            sample: pythonnet-demo
          - os: macos-latest
            sample: pythonnet-demo
          - os: ubuntu-latest
            sample: service
          - os: macos-latest
            sample: service
        branch: [develop]
    name: ${{ matrix.sample }}-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.architecture }}
    runs-on: ${{ matrix.os }}
    steps:
      -
        name: Checkout cx_Freeze
        uses: actions/checkout@v2
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
      -
        name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      -
        name: Restore wheelhouse from cache
        uses: actions/cache@v2
        with:
          path: wheelhouse/*
          key: wheelhouse-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.architecture }}-${{ hashFiles('**/*.py', '**/*.c', '**/*.rst') }}
          restore-keys: wheelhouse-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.architecture }}-
      -
        name: Install Linux libraries
        if: runner.os == 'Linux'
        run: >-
          sudo apt-get install -y
          libdbus-1-3 libxkbcommon-x11-0 libxcb-icccm4
          libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0
          libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0
          libsdl2-2.0-0
          imagemagick-6.q16
          gnome-screenshot
      -
        name: Freeze and run "${{ matrix.sample }}"
        id: freeze-and-run
        env:
          QT_DEBUG_PLUGINS: 1
          DISPLAY: ':99.0'
        run: |
          echo "::group::Install pipenv and create a virtal environment"
          pushd cx_Freeze/samples/${{ matrix.sample }}
          pip install pipenv
          if [ "$OSTYPE" == "msys" ] ; then
            PYTHON=$(cygpath -w `which python`)
          else
            PYTHON=$(which python)
          fi
          pipenv --python $PYTHON --site-packages
          #pipenv install importlib-metadata wheel
          popd
          echo "::endgroup::"
          ./ci/build-test-one.sh ${{ matrix.sample }} || echo "::set-output name=status::$?"
          cd cx_Freeze/samples/${{ matrix.sample }}
          mv build/*/*.png . || true
          mv build/*/*.log . || true
        shell: bash
      -
        name: Upload the snapshots and logs
        uses: actions/upload-artifact@v2
        with:
          name: screensnapshots
          path: |
            ./cx_Freeze/samples/${{ matrix.sample }}/*.png
            ./cx_Freeze/samples/${{ matrix.sample }}/*.log
          if-no-files-found: ignore
      -
        name: Status
        run: exit ${{ steps.freeze-and-run.outputs.status }}
        shell: bash
