name: Build wheel

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15]
        architecture: [universal2]
        python-version: ["39", "310"]
    name: Build [${{ matrix.os }} ${{ matrix.architecture }}][Python ${{ matrix.python-version }}]
    runs-on: ${{ matrix.os }}
    steps:
      -
        uses: actions/checkout@v2
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
      -
        name: Install MacPorts
        run: |
          curl _L https://github.com/macports/macports-base/releases/download/v2.7.1/MacPorts-2.7.1-10.15-Catalina.pkg -O
          #chmod +x MacPorts-2.7.1-10.15-Catalina.pkg
          ls -l
          sudo installer -pkg $(pwd)/MacPorts-2.7.1-10.15-Catalina.pkg -target /
      -
        name: Install python
        run: |
          sudo port install python${{ matrix.python-version }}
      -
        name: Variables
        run: |
          declare || true
          python -m sysconfig
      -
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build setuptools
      -
        name: Build the wheel
        run: python -m build -o wheelhouse
      -
        name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: cx-freeze-wheelhouse
          path: wheelhouse
