name: 1-Build wheels

on:
  #push:
  #  branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9, "3.10.0-rc.1"]
        architecture: [x64, x86]
        exclude:
          - os: ubuntu-latest
            architecture: x86
          - os: macos-latest
            architecture: x86
    name: Build wheel ${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.architecture }}
    runs-on: ${{ matrix.os }}
    steps:
      -
        uses: actions/checkout@v2
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
      -
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      -
        uses: actions/cache@v2
        with:
          path: wheelhouse/*
          key: wheelhouse-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.architecture }}-${{ hashFiles('**/*.py', '**/*.c', '**/*.rst', '**/*.sh') }}
      -
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U importlib-metadata setuptools wheel
        shell: bash
      -
        name: Install or Build cx_Logging
        if: runner.os == 'Windows'
        run: |
          if [[ ${{ matrix.python-version }} == 3.10* ]] ; then
            git clone https://github.com/anthony-tuininga/cx_Logging.git
            pushd cx_Logging
            python setup.py build
            python setup.py bdist_wheel -d ../wheelhouse
            popd
          fi
          pip install cx_Logging
        shell: bash
      -
        name: Build the wheel
        run: pip wheel . --no-deps -v --wheel-dir wheelhouse
        shell: bash
      -
        name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: cx-freeze-wheelhouse
          path: wheelhouse
      -
        name: Update the cache with external files
        working-directory: wheelhouse
        run: |
          if ! [ -e Pillow-8.3.1-cp310-cp310-win_amd64.whl ] ; then
            curl https://download.lfd.uci.edu/pythonlibs/y2rycu7g/Pillow-8.3.1-cp310-cp310-win_amd64.whl -O
          fi
          if ! [ -e numpy-1.21.2+mkl-cp310-cp310-win_amd64.whl ] ; then
            curl https://download.lfd.uci.edu/pythonlibs/y2rycu7g/numpy-1.21.2+mkl-cp310-cp310-win_amd64.whl -O
          fi
          if ! [ -e pandas-1.3.2-cp310-cp310-win_amd64.whl ] ; then
            curl https://download.lfd.uci.edu/pythonlibs/y2rycu7g/pandas-1.3.2-cp310-cp310-win_amd64.whl -O
          fi
          if ! [ -e Pillow-8.3.1-cp310-cp310-win32.whl ] ; then
            curl https://download.lfd.uci.edu/pythonlibs/y2rycu7g/Pillow-8.3.1-cp310-cp310-win32.whl -O
          fi
          if ! [ -e numpy-1.21.2+mkl-cp310-cp310-win32.whl ] ; then
            curl https://download.lfd.uci.edu/pythonlibs/y2rycu7g/numpy-1.21.2+mkl-cp310-cp310-win32.whl -O
          fi
          if ! [ -e pandas-1.3.2-cp310-cp310-win32.whl ] ; then
            curl https://download.lfd.uci.edu/pythonlibs/y2rycu7g/pandas-1.3.2-cp310-cp310-win32.whl -O
          fi
        shell: bash
