name: Build wheel

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]
        python-version: [3.6, 3.7, 3.8, 3.9]
        architecture: ['x86', 'x64']
    name: "Python ${{ matrix.python-version }} on ${{ matrix.architecture }}"
    runs-on: ${{ matrix.os }}
    env:
      RUNNER_OS: ${{ toJSON(runner.os) }}
    steps:
      - uses: actions/checkout@v2
        with:
          repository: marcelotduarte/cx_Freeze
          ref: develop
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ $RUNNER_OS == 'Windows' ] ; then
            pip install -U setuptools wheel
          else
            pip install cibuildwheel==1.8.0
          fi
        shell: bash
      - name: Build the wheel
        run: |
          if [ $RUNNER_OS == 'Windows' ] ; then
            pip install .
            python setup.py bdist_wheel --dist-dir wheelhouse
          else
            python -m cibuildwheel --output-dir wheelhouse
          fi
      - name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: wheelhouse
          path: wheelhouse
  publish:
    needs: build
    runs-on: ubuntu-latest
    name: "Python 3.6"
    steps:
      - uses: actions/checkout@v2
        with:
          repository: marcelotduarte/cx_Freeze
          ref: develop
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools
      - name: Download the artifact
        uses: actions/download-artifact@v2
        with:
          name: wheelhouse
          path: wheelhouse
      - name: Build the sdist
        run: |
          python setup.py sdist --dist-dir wheelhouse
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: wheelhouse
      - name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: wheelhouse
          path: wheelhouse
