name: Build packages

on:
  schedule:
    # run every day at 7:30AM UTC
    - cron:  '30 7 * * *'
  workflow_dispatch:

jobs:

  build_wheel:
    name: Build wheels
    uses: ./.github/workflows/build-wheel.yml
    with:
      branch: develop

  build_wheel_windows_cx_logging_31:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    name: Build cx_Logging [${{ matrix.os }}]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop
          repository: marcelotduarte/cx_Logging

      - uses: actions/setup-python@v5
        with:
          cache: 'pip'
          python-version: "3.12"

      - name: Install cibuildwheel
        run: python -m pip install "cibuildwheel>=2.13.1"

      - name: Build wheels
        env:
          CIBW_BUILD: "cp312*"
        run: python -m cibuildwheel --output-dir wheelhouse --prerelease-pythons

      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: cx-logging-wheelhouse
          path: wheelhouse

  build_msys2:
    name: Build msys2
    uses: ./.github/workflows/build-packages-msys2.yml
    with:
      branch: develop

  conda_recipe:
    name: Generate conda-forge recipe
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: marcelotduarte/cx_freeze-feedstock

      - uses: actions/checkout@v4
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
          path: recipe/cx_Freeze

      - name: Prepare recipe
        id: recipe
        working-directory: recipe
        run: |
          pushd cx_Freeze/cx_Freeze
          VERSION=$(grep "__version__ = " __init__.py | sed 's/-/./' | awk -F\" '{print $2}')
          popd
          sed -i "/set version/c\{% set version = \"$VERSION\" %}" meta.yaml
          sed -i '/number:/c\  number: 0' meta.yaml
          sed -i '/url:/c\  git_url: https://github.com/marcelotduarte/cx_Freeze.git' meta.yaml
          sed -i '/sha256:/c\  git_rev: develop' meta.yaml
          echo "meta=$(base64 --wrap=0 meta.yaml)" >> $GITHUB_OUTPUT
          cp meta.yaml meta_path.yaml
          sed -i '/git_url:/c\  path: ./cx_Freeze' meta_path.yaml
          sed -i '/git_rev:/c\  #' meta_path.yaml
          echo "meta_path=$(base64 --wrap=0 meta_path.yaml)" >> $GITHUB_OUTPUT
          git diff

      - name: List 'unix' configurations
        id: unix
        run: |
          CONFIGS=""
          for CONFIG in .ci_support/linux_*.yaml; do
            name=${CONFIG:12:-5}
            python_and_version=$(echo $name|awk -F_ '{print $3}')
            version="${python_and_version:8:-1}"
            CONFIGS="${CONFIGS}{\"name\":\"${name}\",\"version\":\"${version}\",\"os\":\"ubuntu\"}, "
          done
          for CONFIG in .ci_support/osx_*.yaml; do
            name=${CONFIG:12:-5}
            python_and_version=$(echo $name|awk -F_ '{print $3}')
            version="${python_and_version:6:-1}"
            CONFIGS="${CONFIGS}{\"name\":\"${name}\",\"version\":\"${version}\",\"os\":\"macos\"}, "
          done
          echo "config=[${CONFIGS::-2}]" >> $GITHUB_OUTPUT

      - name: List 'windows' configurations
        id: win
        run: |
          CONFIGS=""
          for CONFIG in .ci_support/win_*.yaml; do
            name=${CONFIG:12:-5}
            python_and_version=$(echo $name|awk -F_ '{print $3}')
            version="${python_and_version:6:-1}"
            #if [ "$version" == "3.11" ]; then
            #  continue
            #fi
            CONFIGS="${CONFIGS}{\"name\":\"${name}\",\"version\":\"${version}\",\"os\":\"windows\"}, "
          done
          echo "config=[${CONFIGS::-2}]" >> $GITHUB_OUTPUT
    outputs:
      data: ${{ steps.recipe.outputs.meta }}
      data_path: ${{ steps.recipe.outputs.meta_path }}
      unix: ${{ steps.unix.outputs.config }}
      win: ${{ steps.win.outputs.config }}

  build_conda_unix:
    needs: [conda_recipe]
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJSON(needs.conda_recipe.outputs.unix) }}
    name: Build ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}-latest

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: actions/checkout@v4
        with:
          repository: marcelotduarte/cx_freeze-feedstock

      - uses: actions/checkout@v4
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
          path: recipe/cx_Freeze

      - name: Update recipe
        working-directory: recipe
        run: echo ${{ needs.conda_recipe.outputs.data_path }} | base64 -d>meta.yaml

      - run: cat recipe/meta.yaml

      - name: Build the conda package
        run: python build-locally.py ${{ matrix.config.name }}

      - name: Move to build_artifacts
        if: matrix.config.os == 'macos'
        run: |
          mkdir -p build_artifacts
          mv miniforge3/conda-bld/* build_artifacts/

      - run: ls -l build_artifacts

      - name: Upload the conda artifact
        uses: actions/upload-artifact@v4
        with:
          name: cx-freeze-conda-${{ matrix.config.name }}
          path: |
            ./build_artifacts/*/cx_freeze*.conda
            ./build_artifacts/*/cx_freeze*.tar.bz2
            !./build_artifacts/pkg_cache/*

  build_conda_windows:
    needs: [conda_recipe]
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJSON(needs.conda_recipe.outputs.win) }}
    name: Build ${{ matrix.config.name }}
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ${{ matrix.config.os }}-latest

    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: freeze-${{ matrix.config.name }}
          python-version: ${{ matrix.config.version }}
          channels: conda-forge

      - run: conda info

      - run: conda install -c conda-forge conda-build

      - uses: actions/checkout@v4
        with:
          repository: marcelotduarte/cx_freeze-feedstock

      - name: Update recipe
        working-directory: recipe
        run: echo ${{ needs.conda_recipe.outputs.data }} | base64 -d>meta.yaml

      - run: cat recipe/meta.yaml

      - name: Build the conda package
        run: |
          mkdir -p build_artifacts
          conda build -c conda-forge recipe --output-folder build_artifacts

      - run: ls -l build_artifacts

      - name: Upload the conda artifact
        uses: actions/upload-artifact@v4
        with:
          name: cx-freeze-conda-${{ matrix.config.name }}
          path: |
            ./build_artifacts/*/cx_freeze*.conda
            ./build_artifacts/*/cx_freeze*.tar.bz2
            !./build_artifacts/pkg_cache/*

  build_conda_index:
    needs:
      # to build the index
      - build_conda_unix
      - build_conda_windows
      # to wait for all artifacts
      - build_msys2
      - build_wheel
      - build_wheel_windows_cx_logging_31
    strategy:
      fail-fast: false
    name: Conda index
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest

    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: freeze-index
          python-version: "3.11"
          channels: conda-forge

      - name: Download all conda artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - run: ls -l artifacts/*/

      - name: Install conda build
        run: conda install -c conda-forge conda-build

      - name: Run conda index
        run: |
          mkdir -p build_artifacts
          cp -auv artifacts/cx-freeze-conda-*/* build_artifacts/
          conda index -s linux-64 -s osx-64 -s osx-arm64 -s win-64 build_artifacts

      - run: ls -l build_artifacts

      - name: Upload repository data to the conda artifact
        uses: actions/upload-artifact@v4
        with:
          name: cx-freeze-conda
          path: ./build_artifacts/*/*

  packages:
    needs:
      - build_conda_index
    runs-on: ubuntu-latest
    name: Update packages repository

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: marcelotduarte/packages
          token: ${{ secrets.PUSH }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Recreate branch gh-pages
        run: |
          git config user.name "Marcelo Duarte"
          git config user.email marcelotduarte@users.noreply.github.com
          git branch -D gh-pages || true
          git push origin :gh-pages || true
          git checkout --orphan gh-pages

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Download the LIEF wheels
        env:
          LIEF_LINK: https://lief.s3-website.fr-par.scw.cloud
        run: |
          mkdir lief
          cd lief
          for f in $(
            curl $LIEF_LINK/latest/lief/ | grep -Eo "href=\"(.*win.*)\"" | cut -c"7-" | cut -d \" -f 1
          ); do
            curl -O $LIEF_LINK$f
          done

      - name: Create packages template
        run: |
          # cx_Logging wheels
          mkdir -p cx-logging
          mv artifacts/cx-logging-*/* cx-logging/
          python make_index.py cx-logging --base cx_Logging
          # msys2 packages (process before wheels)
          mkdir -p msys2
          mv artifacts/cx-freeze-msys2-*/* msys2/
          python make_index.py msys2 --base python-cx-freeze --mask "*.tar.zst"
          # conda packages (process before wheels)
          mkdir -p conda
          mv artifacts/cx-freeze-conda/* conda/
          python make_index.py conda --mask "cx_freeze*.conda" --mask "cx_freeze*.tar.bz2"
          # pip wheels
          mkdir -p cx-freeze
          mv artifacts/cx-freeze-pip-*/* cx-freeze/
          python make_index.py cx-freeze --base cx_Freeze
          # LIEF wheels
          python make_index.py lief --base LIEF

          # cleanup
          rm make_index.py
          rm -rf artifacts

          # configuration
          echo "theme: jekyll-theme-architect">_config.yml

          # template
          VERSION=$(ls cx-freeze | (read name; echo $name) | sed 's/-/ /g' | awk '{print $2}')
          echo -e "# Development packages for cx_Freeze $VERSION\n">index.md
          echo -e "Development wheels for [cx_Freeze](cx-freeze/index.md).\n">>index.md
          echo -e "Development packages for MSYS2 [python-cx-freeze](msys2/index.md).\n">>index.md
          echo -e "Development packages for conda-forge [cx_freeze](conda/index.md).\n">>index.md
          echo -e "# Packages for cx_Logging 3.1 \[Windows\]\[Python 3.12\]\n">>index.md
          echo -e "Unofficial wheels for [cx_Logging](cx-logging/index.md).\n">>index.md
          echo -e "# Packages for LIEF \[Windows\]\[Python 3.8-3.12\]\n">>index.md
          echo -e "Development wheels for [LIEF](lief/index.md).\n">>index.md

      - name: Publish cx_Freeze packages
        run: |
          git add .
          git commit -m "Publish cx_Freeze packages"
          git push --set-upstream origin gh-pages
