name: Build-3-conda

on:
  #push:
  #  branches: [ main ]
  workflow_dispatch:

jobs:
  recipe:
    name: Generate recipe
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
        with:
          repository: marcelotduarte/cx_freeze-feedstock
      -
        uses: actions/checkout@v2
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
          path: cx_Freeze
      -
        name: Prepare recipe
        id: recipe
        run: |
          pushd cx_Freeze/cx_Freeze
          VERSION=$(grep "__version__ = " __init__.py | sed 's/-/./' | awk -F\" '{print $2}')
          popd
          pushd recipe
          sed -i "/set version/c\{% set version = \"$VERSION\" %}" meta.yaml
          sed -i '/url:/c\  git_url: https://github.com/marcelotduarte/cx_Freeze.git' meta.yaml
          sed -i '/sha256:/c\  git_rev: develop' meta.yaml
          sed -i '/number:/c\  number: 0' meta.yaml
          echo "::set-output name=encoded::$(base64 --wrap=0 meta.yaml)"
          popd
          git diff
      -
        name: List configurations
        id: config
        run: |
          LINUX_64=
          pushd .ci_support
          for CONFIG in *.yaml; do
            echo ${CONFIG::8} ${CONFIG::-5}
            if [ "${CONFIG::8}" == "linux_64" ] ; then
              echo ${CONFIG::-5}
              LINUX_64="${LINUX_64},${CONFIG::-5}"
            fi
          done
          popd
          echo ${LINUX_64:1:}
          echo "::set-output name=linux_64::[${LINUX_64:1:}]"
    outputs:
      data: ${{ steps.recipe.outputs.encoded }}
      linux_64: ${{ steps.config.outputs.linux_64 }}

  build_linux_64:
    needs: [recipe]
    strategy:
      fail-fast: false
      matrix:
        linux_64: ${{ fromJSON(needs.recipe.outputs.linux_64) }}
    name: Build ${{ matrix.linux_64 }}
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
        with:
          repository: marcelotduarte/cx_freeze-feedstock
      -
        uses: actions/setup-python@v2
      -
        name: Update recipe
        run: echo ${{ needs.recipe.outputs.data }} | base64 -d>recipe/meta.yaml
      -
        run: cat recipe/meta.yaml
      -
        name: Build the conda package
        run: |
          for CONFIG in ${{ matrix.linux_64 }} ; do
            echo $CONFIG
          done
      -
        name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: cx-freeze-conda
          path: ./*/cx_freeze*.tar.bz2

  build_osx_64_and_win_64:
    needs: [recipe]
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
        #python-version: ["3.7", "3.8", "3.9", "3.10"]
        python-version: ["3.8"]
        architecture: [x64]
    name: Build ${{ matrix.os }}-${{ matrix.architecture }}-${{ matrix.python-version }}
    defaults:
      run:
        shell: bash -l {0}
    env:
      KEY_BASE: ${{ matrix.os }}-${{ matrix.architecture }}-${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    steps:
      -
        uses: actions/checkout@v2
        with:
          repository: marcelotduarte/cx_freeze-feedstock
      -
        name: Update recipe
        run: echo ${{ needs.recipe.outputs.data }} | base64 -d>recipe/meta.yaml
      -
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: freeze-${{ env.KEY_BASE }}
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
          channels: conda-forge
      -
        run: conda info
      -
        run: conda install -c conda-forge conda-build
      -
        name: Build the conda package
        run: conda build -c conda-forge recipe --output-folder .
      -
        name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: cx-freeze-conda
          path: ./*/cx_freeze*.tar.bz2
