name: 2.2-Tests on Windows - numpy+mkl

on:
  #push:
  #  branches: [ main ]
  workflow_dispatch:

jobs:
  test1:
    name: Test

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: [3.8, 3.9]
        architecture: [x64]

    runs-on: ${{ matrix.os }}

    steps:
      -
        name: Checkout cx_Freeze
        uses: actions/checkout@v2
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
      -
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      -
        name: Restore wheelhouse from cache
        uses: actions/cache@v2
        with:
          path: wheelhouse/*
          key: wheelhouse-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.architecture }}-${{ hashFiles('**/*.py', '**/*.c', '**/*.rst') }}
          restore-keys: wheelhouse-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.architecture }}-
      -
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U importlib-metadata setuptools wheel cx-logging
          pip install --no-index -f wheelhouse cx-freeze --no-deps
          cxfreeze --version
      -
        run: python -m sysconfig
      -
        name: Install numpy+mkl and pandas
        run: |
          if [ "${{ matrix.python-version }}" == "3.8" ] ; then
              curl https://download.lfd.uci.edu/pythonlibs/q4trcu4l/numpy-1.20.3+mkl-cp38-cp38-win_amd64.whl -o wheelhouse/numpy-1.20.3+mkl-cp38-cp38-win_amd64.whl
          else
              curl https://download.lfd.uci.edu/pythonlibs/q4trcu4l/numpy-1.20.3+mkl-cp39-cp39-win_amd64.whl -o wheelhouse/numpy-1.20.3+mkl-cp39-cp39-win_amd64.whl
          fi
          pip install --no-index -f wheelhouse numpy
          pip install pandas
        shell: bash
      -
        name: Freeze pandas sample (numpy+mkl)
        working-directory: cx_Freeze/samples/pandas
        run: python setup.py build_exe --silent
      -
        name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: frozen-pandas-${{ matrix.python-version }}
          path: ./cx_Freeze/samples/pandas/build/*/**
      -
        name: Run pandas sample (numpy+mkl)
        working-directory: cx_Freeze/samples/pandas/build
        run: ./exe.win-amd64-${{ matrix.python-version }}/test_pandas.exe

  test2:
    name: Test in virtual environment

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: [3.8, 3.9]
        architecture: [x64]

    runs-on: ${{ matrix.os }}

    steps:
      -
        name: Checkout cx_Freeze
        uses: actions/checkout@v2
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
      -
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      -
        name: Restore wheelhouse from cache
        uses: actions/cache@v2
        with:
          path: wheelhouse/*
          key: wheelhouse-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.architecture }}-${{ hashFiles('**/*.py', '**/*.c', '**/*.rst') }}
          restore-keys: wheelhouse-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.architecture }}-
      -
        name: Create venv with dependencies
        run: |
          python -m venv venv
          source venv/scripts/activate
          python -m pip install --upgrade pip
          pip install -U importlib-metadata setuptools wheel cx-logging
          pip install --no-index -f wheelhouse cx-freeze --no-deps
          cxfreeze --version
        shell: bash
      -
        run: |
          source venv/scripts/activate
          python -m sysconfig
        shell: bash
      -
        name: Install numpy+mkl and pandas
        run: |
          source venv/scripts/activate
          if [ "${{ matrix.python-version }}" == "3.8" ] ; then
              curl https://download.lfd.uci.edu/pythonlibs/q4trcu4l/numpy-1.20.3+mkl-cp38-cp38-win_amd64.whl -o wheelhouse/numpy-1.20.3+mkl-cp38-cp38-win_amd64.whl
          else
              curl https://download.lfd.uci.edu/pythonlibs/q4trcu4l/numpy-1.20.3+mkl-cp39-cp39-win_amd64.whl -o wheelhouse/numpy-1.20.3+mkl-cp39-cp39-win_amd64.whl
          fi
          pip install --no-index -f wheelhouse numpy
          pip install pandas
        shell: bash
      -
        name: Freeze pandas sample (numpy+mkl)
        working-directory: cx_Freeze/samples/pandas
        run: |
          source venv/scripts/activate
          python setup.py build_exe --silent
      -
        name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: frozen-pandas-${{ matrix.python-version }}
          path: ./cx_Freeze/samples/pandas/build/*/**
      -
        name: Run pandas sample (numpy+mkl)
        working-directory: cx_Freeze/samples/pandas/build
        run: ./exe.win-amd64-${{ matrix.python-version }}/test_pandas.exe
