name: Build wheel

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        architecture: ['x86', 'x64']
    name: "Python ${{ matrix.python-version }} on ${{ matrix.architecture }}"
    steps:
      - uses: actions/checkout@v2
        with:
          repository: marcelotduarte/cx_Freeze
          ref: develop
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools wheel
      - name: Build the wheel
        run: |
          pip install .
          python setup.py bdist_wheel
      - name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: wheelhouse
          path: dist
  publish:
    needs: windows
    runs-on: ubuntu-latest
    name: "Python 3.6"
    steps:
      - uses: actions/checkout@v2
        with:
          repository: marcelotduarte/cx_Freeze
          ref: develop
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools
      - name: Download the artifact
        uses: actions/download-artifact@v2
        with:
          name: wheelhouse
          path: dist
      - name: Build the sdist
        run: |
          python setup.py sdist
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: dist
      - name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: wheelhouse
          path: dist
