name: Build-3-conda

on:
  #push:
  #  branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        #python-version: ["3.7", "3.8", "3.9", "3.10"]
        python-version: ["3.8"]
        architecture: [x64]
    name: Build ${{ matrix.os }}-${{ matrix.architecture }}-${{ matrix.python-version }}
    defaults:
      run:
        shell: bash -l {0}
    env:
      KEY_BASE: ${{ matrix.os }}-${{ matrix.architecture }}-${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    steps:
      -
        uses: actions/checkout@v2
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
      -
        uses: actions/checkout@v2
        with:
          repository: marcelotduarte/cx_freeze-feedstock
          path: cx_freeze-feedstock
      -
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: freeze-${{ env.KEY_BASE }}
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
          channels: conda-forge
      -
        uses: actions/cache@v2
        with:
          key: conda-${{ env.KEY_BASE }}-${{ github.sha }}
          path: ./*/cx_freeze*.tar.bz2
      -
        run: conda info
      -
        run: conda install -c conda-forge conda-build
      -
        name: Prepare recipe
        if: runner.os != 'macOS'
        run: |
          VERSION=$(grep "__version__ = " cx_Freeze/__init__.py | sed 's/-/./' | awk -F\" '{print $2}')
          pushd cx_freeze-feedstock/recipe
          sed -i "/set version/c\{% set version = \"$VERSION\" %}" meta.yaml
          sed -i '/url:/c\  path: ../..' meta.yaml
          sed -i '/.*sha256.*/d' meta.yaml
          sed -i '/number:/c\  number: 0' meta.yaml
          git diff
      -
        name: Prepare recipe
        if: runner.os == 'macOS'
        working-directory: recipe
        run: |
          VERSION=$(grep "__version__ = " cx_Freeze/__init__.py | sed 's/-/./' | awk -F\" '{print $2}')
          # sed on macOS differ from Linux
          sed -i '' "/.*set version.*/d" meta.yaml
          cp meta.yaml meta.tmp
          echo "{% set version = \"$VERSION\" %}">meta.yaml
          cat meta.tmp>>meta.yaml
          rm meta.tmp
          sed -i '' '/url:/c\  path: ../..' meta.yaml
          sed -i '' '/.*sha256.*/d' meta.yaml
          sed -i '' '/number:/c\  number: 0' meta.yaml
          git diff
      -
        name: Build the conda package
        run: conda build -c conda-forge recipe --output-folder .
      -
        name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: cx-freeze-conda
          path: ./*/cx_freeze*.tar.bz2
