name: Build wheel

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build_wheel_windows:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        python-version: ["3.9", "3.10"]
        architecture: [x64, arm64]
    name: Build [${{ matrix.os }} ${{ matrix.architecture }}][Python ${{ matrix.python-version }}]
    runs-on: ${{ matrix.os }}
    steps:
      -
        uses: actions/checkout@v2
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
      -
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      -
        name: Variables
        run: |
          declare || true
          python -m sysconfig
        shell: bash
      -
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade build setuptools
        shell: bash
      -
        name: Build the wheel
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: "1"
          MACOSX_DEPLOYMENT_TARGET: "10.9"
        run: |
          if [ ${{ matrix.python-version }} != "36" ] &&
             [ ${{ matrix.python-version }} != "37" ] ; then
            if [ ${{ matrix.architecture }} == "arm64" ] ; then
              export _PYTHON_HOST_PLATFORM="macosx-11.0-arm64"
              export ARCHFLAGS="-arch arm64"
            elif [ ${{ matrix.architecture }} == "universal2" ] ; then
              export _PYTHON_HOST_PLATFORM="macosx-10.9-universal2"
              export ARCHFLAGS="-arch arm64 -arch x86_64"
            else
              export _PYTHON_HOST_PLATFORM="macosx-10.9-x86_64"
              export ARCHFLAGS="-arch x86_64"
            fi
          fi
          python -m build -o wheelhouse
      -
        name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: cx-freeze-wheelhouse
          path: wheelhouse

  build_wheel_unix:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
    name: Build [${{ matrix.os }}]
    runs-on: ${{ matrix.os }}
    steps:
      -
        uses: actions/checkout@v2
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
      -
        uses: actions/setup-python@v2
      -
        name: Variables
        run: |
          declare || true
          python -m sysconfig
      -
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel==2.3.1
      -
        name: Build the wheel
        env:
          CIBW_BUILD: "cp3*-macosx_*"
          CIBW_ARCHS: "auto universal2 arm64"

        run: python -m cibuildwheel
      -
        name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: cx-freeze-cibuildwheel
          path: wheelhouse

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11]
        architecture: [universal2]
        python-version: ["39", "310"]
    name: Build [${{ matrix.os }} ${{ matrix.architecture }}][Python ${{ matrix.python-version }}]
    runs-on: ${{ matrix.os }}
    steps:
      -
        uses: actions/checkout@v2
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
      -
        name: Install MacPorts
        run: |
          curl -LO https://github.com/macports/macports-base/releases/download/v2.7.1/MacPorts-2.7.1-11-BigSur.pkg
          sudo installer -pkg MacPorts-2.7.1-11-BigSur.pkg -target /
          echo "/opt/local/bin:/opt/local/sbin" >> $GITHUB_PATH
      -
        name: Install python
        run: |
          sudo port install python${{ matrix.python-version }} +universal
          sudo port select --set python python${{ matrix.python-version }}
      -
        name: Variables
        run: |
          declare || true
          python -m sysconfig
      -
        name: Install dependencies
        run: |
          sudo port install py${{ matrix.python-version }}-pip +universal
          sudo port select --set pip pip${{ matrix.python-version }}
          sudo port install py${{ matrix.python-version }}-build +universal
      -
        name: Build the wheel
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: "1"
          MACOSX_DEPLOYMENT_TARGET: "10.9"
        run: |
          if [ ${{ matrix.python-version }} != "36" ] &&
             [ ${{ matrix.python-version }} != "37" ] ; then
            if [ ${{ matrix.architecture }} == "arm64" ] ; then
              export _PYTHON_HOST_PLATFORM="macosx-11.0-arm64"
              export ARCHFLAGS="-arch arm64"
            elif [ ${{ matrix.architecture }} == "universal2" ] ; then
              export _PYTHON_HOST_PLATFORM="macosx-10.9-universal2"
              export ARCHFLAGS="-arch arm64 -arch x86_64"
            else
              export _PYTHON_HOST_PLATFORM="macosx-10.9-x86_64"
              export ARCHFLAGS="-arch x86_64"
            fi
          fi
          python -m build -o wheelhouse
      -
        name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: cx-freeze-macports
          path: wheelhouse
