name: Build wheel

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  windows:
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        architecture: [x86, x64]
    name: Build wheel cp${{ matrix.python-version }}-win${{ matrix.architecture }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U importlib-metadata setuptools wheel
      - name: Build the wheel
        run: |
          pip wheel . --no-deps -v --wheel-dir wheelhouse
      - name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: cx-freeze-wheelhouse
          path: wheelhouse
  macos:
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        architecture: [x64]
    name: Build wheel cp${{ matrix.python-version }}-macos${{ matrix.architecture }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U importlib-metadata setuptools wheel
      - name: Info
        run: |
          xcodebuild -showsdks
          set
          python -m sysconfig
      - name: Build the wheel
        #env: 
        #  MACOSX_DEPLOYMENT_TARGET: 10.9
        #  _PYTHON_HOST_PLATFORM: macosx-10.9-x86_64
        run: pip wheel . --no-deps -v --wheel-dir wheelhouse
      - name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: cx-freeze-wheelhouse
          path: wheelhouse
  macos_cibuildwheel:
    name: Build wheel using cibuildwheel on macOS
    strategy:
      matrix:
        platform: [x86_64]
    runs-on: macos-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel==1.8.0
      -
        name: Build the wheel
        env:
          CIBW_BUILD: cp3*-m*_x86_64
          CIBW_SKIP: cp35*
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BEFORE_BUILD: python -m pip install --upgrade pip && pip install -U importlib-metadata setuptools wheel && python -m sysconfig
        run: |
          python -m cibuildwheel --output-dir wheelhouse .
      - name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: cx-freeze-wheelhouse
          path: wheelhouse
  linux:
    name: Build wheel using manylinux2010
    strategy:
      matrix:
        platform: [x86_64]
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel==1.8.0
      -
        name: Get the docker image from cache
        uses: actions/cache@v2
        with:
          key: ${{ matrix.platform }}-832d012f47972739e31ae60f98c5b26a120b17b8f963c3cfac573312d2214e61-08d852fc3239b55c8d36b8b1ad97dd6de59856c6c98573d142476da5980d3899
          path: /tmp/docker
      -
        name: Load the docker image
        env:
          PLATFORM: ${{ matrix.platform }}
          IMAGE_NAME: manylinux2010_${{ matrix.platform }}
        run: docker load -i /tmp/docker/${IMAGE_NAME}.tar
      -
        name: Build the wheel
        env:
          CIBW_BUILD: cp3*-m*_x86_64
          CIBW_SKIP: cp35*
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BEFORE_BUILD: python -m pip install --upgrade pip && pip install -U importlib-metadata setuptools wheel && python -m sysconfig
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2010_${{ matrix.platform }}
        run: |
          python -m cibuildwheel --output-dir wheelhouse .
      - name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: cx-freeze-wheelhouse
          path: wheelhouse
  publish:
    needs: [windows, macos, macos_cibuildwheel, linux]
    runs-on: ubuntu-20.04
    name: "Publish"
    steps:
      - uses: actions/checkout@v2
        with:
          repository: marcelotduarte/cx_Freeze
          ref: develop
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools
      - name: Download the artifact
        uses: actions/download-artifact@v2
        with:
          name: cx-freeze-wheelhouse
          path: wheelhouse
      - name: Build the sdist
        run: |
          python setup.py sdist --dist-dir wheelhouse
      - name: Build the docs
        run: |
          pip install . --no-deps
          make -C doc
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: wheelhouse
      - name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: cx-freeze-wheelhouse
          path: wheelhouse
