name: Build wheel

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    name: Build wheels - ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11.0]
    runs-on: ${{ matrix.os }}
    steps:
      -
        uses: actions/checkout@v2
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
      -
        uses: actions/setup-python@v2
      -
        name: Variables
        run: |
          declare || true
          python -m sysconfig
        shell: bash
      -
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel==2.3.1
      -
        name: Build the wheel
        env:
          CIBW_DEPENDENCY_VERSIONS: latest
          CIBW_ENVIRONMENT: MACOSX_DEPLOYMENT_TARGET=11.1
          CIBW_BEFORE_BUILD_MACOS: >-
            find /Library/Frameworks/Python.framework/Versions/3.8 -name '*.a' -print &&
            find /Library/Frameworks/Python.framework/Versions/3.8 -name '*.dylib' -print
          CIBW_BUILD: "cp38*-macosx_*"
        #  #CIBW_ENVIRONMENT: "LDFLAGS=-L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib"
        #  #CIBW_ENVIRONMENT: SDKROOT="/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk"
        run: python -m cibuildwheel --archs x86_64,universal2,arm64
      -
        name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: cx-freeze-wheelhouse
          path: wheelhouse
