name: Build-1-wheel

on:
  #push:
  #  branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
        architecture: [x64, x86]
        exclude:
          - os: ubuntu-latest
            architecture: x86
          - os: macos-latest
            architecture: x86
    name: Build [${{ matrix.os }} ${{ matrix.architecture }}][Python ${{ matrix.python-version }}]
    runs-on: ${{ matrix.os }}
    steps:
      -
        uses: actions/checkout@v2
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
      -
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      -
        name: Variables
        run: |
          declare || true
          python -m sysconfig
        shell: bash
      -
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade build setuptools
        shell: bash
      -
        name: Build the wheel
        if: runner.os != 'Windows' || matrix.python-version != '3.10'
        run: |
          python -m build -o wheelhouse
        shell: bash
      -
        name: Build the wheel [Windows][Python 3.10]
        if: runner.os == 'Windows' && matrix.python-version == '3.10'
        run: |
          pip install --upgrade wheel
          git clone -b 3.0 https://github.com/anthony-tuininga/cx_Logging.git
          python -m build -o wheelhouse -n ./cx_Logging
          pip install -f wheelhouse cx_Logging
          python -m build -o wheelhouse -n .
        shell: bash
      -
        name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: cx-freeze-wheelhouse
          path: wheelhouse/cx_*

  packages:
    needs: build
    runs-on: ubuntu-20.04
    name: Update packages repository
    steps:
      -
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: marcelotduarte/packages
          token: ${{ secrets.PUSH }}
      -
        name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      -
        name: Download the artifact
        uses: actions/download-artifact@v2
        with:
          name: cx-freeze-wheelhouse
          path: wheelhouse
      -
        name: Create packages template
        working-directory: wheelhouse
        run: |
          cp ../make_index.py .
          mkdir -p cx-Freeze
          mv cx_Freeze-* cx-Freeze/
          mkdir -p cx-Logging
          mv cx_Logging-* cx-Logging/
          python make_index.py cx-Freeze
          python make_index.py cx-Logging
          rm make_index.py
          echo "theme: jekyll-theme-architect">_config.yml
          echo "## Packages for cx_Freeze">index.md
          echo "">>index.md
          echo "Nightly packages for [cx_Freeze](cx_Freeze/index.md).">>index.md
          echo "">>index.md
          echo "## Packages for cx_Logging 3.0 \[Windows\]\[Python 3.10\]">>index.md
          echo "">>index.md
          echo "Unofficial [cx_Logging](cx_Logging/index.md) packages.">>index.md
          echo "">>index.md
      -
        name: Publish cx_Freeze packages
        run: |
          git config user.name "Marcelo Duarte"
          git config user.email marcelotduarte@users.noreply.github.com
          git branch -D gh-pages || true
          git push origin :gh-pages || true
          git checkout --orphan gh-pages
          cp -r wheelhouse/* .
          git add cx_Freeze cx_Logging _config.yml index.md
          git commit -m "Publish cx_Freeze packages"
          git push --set-upstream origin gh-pages
        shell: bash
