name: Build wheel

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    name: Build wheels - ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11.0]
    runs-on: ${{ matrix.os }}
    steps:
      -
        uses: actions/checkout@v2
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
      -
        uses: actions/setup-python@v2
      -
        name: Variables
        run: |
          declare || true
          python -m sysconfig
        shell: bash
      -
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel==2.3.1
      -
        name: Build the wheel
        env:
          CIBW_DEPENDENCY_VERSIONS: latest
          CIBW_ENVIRONMENT: >-
            MACOSX_DEPLOYMENT_TARGET=11.0
            MACOSX_SDK_VERSION=12.2
            #SDKROOT=$XCODE_12_DEVELOPER_DIR
          CIBW_BEFORE_BUILD_MACOS: >-
            declare && python -VV && python -m sysconfig &&
            ls -l -h $(find /Library/Frameworks/Python.framework/Versions -name 'libpython3.*.*' -print)
            && ls -l $(find /Library/Frameworks/Python.framework/Versions -name 'Python' -print) &&
            echo "!"
          CIBW_BUILD: "cp39*-macosx_*"
          CIBW_ARCHS_MACOS: universal2
        #  #CIBW_ENVIRONMENT: "LDFLAGS=-L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib"
        #  #CIBW_ENVIRONMENT: SDKROOT="/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk"
        run: python -m cibuildwheel
      -
        name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: cx-freeze-wheelhouse
          path: wheelhouse
