name: 3-Test using MSYS2

on:
  #push:
  #  branches: [ main ]
  workflow_dispatch:

jobs:
  matrix:
    name: Generate matrix of samples
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      -
        uses: actions/checkout@v2
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
      -
        uses: actions/setup-python@v2
      -
        id: set-matrix
        run: |
          import json
          with open("ci/build-test.json") as fp:
              data = json.load(fp)
          samples = json.dumps(list(data.keys()))
          print(f"::set-output name=matrix::{samples}")
        shell: python

  tests:
    needs: [matrix]
    strategy:
      fail-fast: false
      matrix:
        sample: ${{ fromJSON(needs.matrix.outputs.matrix) }}
        sys: [ { msystem: MINGW64, arch: x86_64 }, { msystem: MINGW32, arch: i686 } ]
    name: ${{ matrix.sample }}-${{ matrix.sys.msystem }}
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      -
        name: Checkout cx_Freeze
        uses: actions/checkout@v2
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
      -
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.sys.msystem }}
          #install: >-
            #base-devel
            #mingw-w64-${{ matrix.sys.arch }}-ca-certificates
            #mingw-w64-${{ matrix.sys.arch }}-toolchain
            #mingw-w64-${{ matrix.sys.arch }}-pip
      -
        name: Install dependencies
        run: echo pip install --upgrade cx_Logging
      -
        name: Build the wheel
        run: pip install . --no-deps -v
      -
        name: Freeze and run "${{ matrix.sample }}"
        run: ./ci/build-test-one.sh ${{ matrix.sample }}
