name: Build packages

on:
  schedule:
    # run every day at 7:30AM UTC
    - cron:  '30 7 * * *'

jobs:

  build_packages:
    name: Build packages
    uses: ./.github/workflows/build-packages.yml
    with:
      build_cx_logging: true
      build_lief: false
