name: Build-3-conda

on:
  #push:
  #  branches: [ main ]
  workflow_dispatch:

jobs:
  conda_recipe:
    name: Generate recipe
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
        with:
          repository: marcelotduarte/cx_freeze-feedstock
      -
        uses: actions/checkout@v2
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
          path: recipe/cx_Freeze
      -
        name: Prepare recipe
        id: recipe
        working-directory: recipe
        run: |
          pushd cx_Freeze/cx_Freeze
          VERSION=$(grep "__version__ = " __init__.py | sed 's/-/./' | awk -F\" '{print $2}')
          popd
          sed -i "/set version/c\{% set version = \"$VERSION\" %}" meta.yaml
          sed -i '/number:/c\  number: 0' meta.yaml
          cp meta.yaml meta1.yaml
          sed -i '/url:/c\  git_url: https://github.com/marcelotduarte/cx_Freeze.git' meta1.yaml
          sed -i '/sha256:/c\  git_rev: develop' meta1.yaml
          echo "::set-output name=encoded::$(base64 --wrap=0 meta1.yaml)"
          cp meta.yaml meta2.yaml
          sed -i '/url:/c\  path: ./cx_Freeze' meta2.yaml
          sed -i '/sha256:/c\  #' meta2.yaml
          echo "::set-output name=encoded2::$(base64 --wrap=0 meta2.yaml)"
          git diff
      -
        name: List 'unix' configurations
        id: unix
        run: |
          CONFIGS=""
          for CONFIG in .ci_support/linux_*.yaml; do
            name=${CONFIG:12:-5}
            python_and_version=$(echo $name|awk -F_ '{print $3}')
            version="${python_and_version:8:-1}"
            CONFIGS="${CONFIGS}{\"name\":\"${name}\",\"version\":\"${version}\",\"os\":\"ubuntu\"}, "
          done
          for CONFIG in .ci_support/osx_*.yaml; do
            name=${CONFIG:12:-5}
            python_and_version=$(echo $name|awk -F_ '{print $3}')
            version="${python_and_version:6:-1}"
            CONFIGS="${CONFIGS}{\"name\":\"${name}\",\"version\":\"${version}\",\"os\":\"macos\"}, "
          done
          echo ${CONFIGS::-2}
          echo "[${CONFIGS::-2}]"
          echo "::set-output name=config::[${CONFIGS::-2}]"
      -
        name: List 'win' configurations
        id: win
        run: |
          CONFIGS=""
          for CONFIG in .ci_support/win_*.yaml; do
            name=${CONFIG:12:-5}
            python_and_version=$(echo $name|awk -F_ '{print $3}')
            version="${python_and_version:6:-1}"
            CONFIGS="${CONFIGS}{\"name\":\"${name}\",\"version\":\"${version}\",\"os\":\"windows\"}, "
          done
          echo ${CONFIGS::-2}
          echo "[${CONFIGS::-2}]"
          echo "::set-output name=config::[${CONFIGS::-2}]"
    outputs:
      data: ${{ steps.recipe.outputs.encoded }}
      data2: ${{ steps.recipe.outputs.encoded2 }}
      unix: ${{ steps.unix.outputs.config }}
      win: ${{ steps.win.outputs.config }}

  build_conda_unix:
    needs: [conda_recipe]
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJSON(needs.conda_recipe.outputs.unix) }}
    name: Build ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}-latest
    steps:
      -
        uses: actions/setup-python@v2
      -
        uses: actions/checkout@v2
        with:
          repository: marcelotduarte/cx_freeze-feedstock
      -
        uses: actions/checkout@v2
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
          path: recipe/cx_Freeze
      -
        name: Update recipe
        working-directory: recipe
        run: echo ${{ needs.recipe.outputs.data2 }} | base64 -d>meta.yaml
      -
        run: cat recipe/meta.yaml
      -
        name: Build the conda package
        run: python build-locally.py ${{ matrix.config.name }}
      -
        name: Move to build_artifacts
        if: matrix.config.os == 'macos'
        run: mkdir -p build_artifacts && mv miniforge3/conda-bld/* build_artifacts/
      -
        name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: cx-freeze-conda
          path: ./build_artifacts/*/cx_freeze*.tar.bz2

  build_conda_windows:
    needs: [conda_recipe]
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJSON(needs.conda_recipe.outputs.win) }}
    name: Build ${{ matrix.config.name }}
    defaults:
      run:
        shell: bash -l {0}
    runs-on: windows-latest
    steps:
      -
        uses: actions/checkout@v2
        with:
          repository: marcelotduarte/cx_freeze-feedstock
      -
        uses: actions/checkout@v2
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
          path: recipe/cx_Freeze
      -
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: freeze-${{ matrix.config.name }}
          python-version: ${{ matrix.config.version }}
          #architecture: ${{ matrix.architecture }}
          channels: conda-forge
      -
        run: conda info
      -
        run: conda install -c conda-forge conda-build
      -
        name: Update recipe
        working-directory: recipe
        run: echo ${{ needs.recipe.outputs.data2 }} | base64 -d>meta.yaml
      -
        name: Build the conda package
        run: conda build -c conda-forge recipe --output-folder .
      -
        name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: cx-freeze-conda
          path: ./*/cx_freeze*.tar.bz2
