name: Build-3-conda

on:
  #push:
  #  branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        #python-version: ["3.7", "3.8", "3.9", "3.10"]
        python-version: ["3.8"]
        architecture: [x64]
    name: Build ${{ matrix.os }}-${{ matrix.architecture }}-${{ matrix.python-version }}
    defaults:
      run:
        shell: bash -l {0}
    env:
      KEY_BASE: ${{ matrix.os }}-${{ matrix.architecture }}-${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    steps:
      -
        uses: actions/checkout@v2
        with:
          repository: marcelotduarte/cx_freeze-feedstock
      -
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: freeze-${{ env.KEY_BASE }}
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
          channels: conda-forge
      -
        uses: actions/cache@v2
        with:
          key: conda-${{ env.KEY_BASE }}-${{ github.sha }}
          path: ./*/cx_freeze*.tar.bz2
      -
        run: conda info
      -
        run: conda install conda-build
      -
        name: Prepare recipe
        working-directory: recipe
        run: |
          VERSION="6.11.dev"
          # sed -i differ between Linux and osx, so I do not use it.
          sed "/.*set version.*/d" meta.yaml>meta.tmp
          sed '/url:/c\  git_url: https://github.com/marcelotduarte/cx_Freeze.git' meta.tmp>meta.yaml
          sed '/sha256:/c\  git_rev: develop' meta.yaml>meta.tmp
          sed '/number:/c\  number: 0' meta.tmp>meta.yaml
          cp meta.yaml meta.tmp
          echo "{% set version = \"$VERSION\" %}">meta.yaml
          cat meta.tmp>>meta.yaml
          rm meta.tmp
      -
        name: Build the conda package
        run: conda build recipe --output-folder .
      -
        name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: cx-freeze-conda
          path: ./*/cx_freeze*.tar.bz2
