name: 1-Build wheels

on:
  #push:
  #  branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        #os: [ubuntu-latest, windows-latest, macos-latest]
        #python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
        os: [windows-latest]
        python-version: ["3.9"]
        architecture: [x64, x86]
        #exclude:
        #  - os: ubuntu-latest
        #    architecture: x86
        #  - os: macos-latest
        #    architecture: x86
    name: Build wheel ${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.architecture }}
    runs-on: ${{ matrix.os }}
    steps:
      -
        uses: actions/checkout@v2
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
      -
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      -
        name: Variables
        run: |
          declare || true
          python -m sysconfig
        shell: bash
      -
        uses: actions/cache@v2
        with:
          path: wheelhouse/*
          key: wheelhouse-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.architecture }}-${{ hashFiles('**/*.py', '**/*.c', '**/*.rst', '**/*.sh') }}
      -
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U build importlib-metadata setuptools wheel
        shell: bash
      -
        name: Install or Build cx_Logging
        if: runner.os == 'Windows'
        run: |
          if [[ ${{ matrix.python-version }} == 3.10* ]] ; then
            git clone https://github.com/anthony-tuininga/cx_Logging.git
            pushd cx_Logging
            python setup.py build
            python -m build -x --wheel --outdir ../wheelhouse .
            popd
          fi
          pip install cx_Logging
        shell: bash
      -
        name: Build the wheel
        run: |
          python -m build -x --wheel --outdir wheelhouse .
        shell: bash
      -
        name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: cx-freeze-wheelhouse
          path: wheelhouse/cx_*
      -
        name: Update the cache with external files
        working-directory: wheelhouse
        run: |
          if [ ${{ matrix.architecture }} == x64 ] ; then
            if [ "${{ matrix.python-version }}" == "3.6" ] ; then
              curl https://download.lfd.uci.edu/pythonlibs/x6hvwk7i/cp36/numpy-1.19.5+mkl-cp36-cp36m-win_amd64.whl -O
            elif [ "${{ matrix.python-version }}" == "3.7" ] ; then
                curl https://download.lfd.uci.edu/pythonlibs/x6hvwk7i/numpy-1.21.5+mkl-cp37-cp37m-win_amd64.whl -O
            elif [ "${{ matrix.python-version }}" == "3.8" ] ; then
                curl https://download.lfd.uci.edu/pythonlibs/x6hvwk7i/numpy-1.21.5+mkl-cp38-cp38-win_amd64.whl -O
            elif [ "${{ matrix.python-version }}" == "3.9" ] ; then
                curl https://download.lfd.uci.edu/pythonlibs/x6hvwk7i/numpy-1.21.5+mkl-cp39-cp39-win_amd64.whl -O
            elif [[ ${{ matrix.python-version }} == 3.10* ]] ; then
              curl https://download.lfd.uci.edu/pythonlibs/x6hvwk7i/numpy-1.21.5+mkl-cp310-cp310-win_amd64.whl -O
              #curl https://download.lfd.uci.edu/pythonlibs/x6hvwk7i/Pillow-8.4.0-cp310-cp310-win_amd64.whl -O
              #curl https://download.lfd.uci.edu/pythonlibs/x6hvwk7i/pandas-1.3.5-cp310-cp310-win_amd64.whl -O
            fi
          else
            if [[ ${{ matrix.python-version }} == 3.10* ]] ; then
              curl https://download.lfd.uci.edu/pythonlibs/x6hvwk7i/numpy-1.21.5+mkl-cp310-cp310-win32.whl -O
              #curl https://download.lfd.uci.edu/pythonlibs/x6hvwk7i/Pillow-8.4.0-cp310-cp310-win32.whl -O
              curl https://download.lfd.uci.edu/pythonlibs/x6hvwk7i/pandas-1.3.5-cp310-cp310-win32.whl -O
            fi
          fi
        shell: bash
