name: Build wheel

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    name: Build wheels - ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      -
        uses: actions/checkout@v2
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
      -
        uses: actions/setup-python@v2
      -
        name: Variables
        run: |
          declare || true
          python -m sysconfig
        shell: bash
      -
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel==2.3.1
      -
        name: Build the wheel
        env:
          #CIBW_ENVIRONMENT: "LDFLAGS=-L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib"
          CIBW_ENVIRONMENT: SDKROOT="/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk"
        run: python -m cibuildwheel
      -
        name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: cx-freeze-wheelhouse
          path: wheelhouse
