name: 3-Test using MSYS2

on:
  #push:
  #  branches: [ main ]
  workflow_dispatch:

jobs:
  matrix:
    name: Generate matrix of samples
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      -
        uses: actions/checkout@v2
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
      -
        uses: actions/setup-python@v2
      -
        id: set-matrix
        run: |
          import json
          with open("ci/build-test.json") as fp:
              data = json.load(fp)
          samples = json.dumps(list(data.keys()))
          print(f"::set-output name=matrix::{samples}")
        shell: python

  tests:
    needs: [matrix]
    strategy:
      fail-fast: false
      matrix:
        sample: ${{ fromJSON(needs.matrix.outputs.matrix) }}
        #sys: [ { msystem: MINGW32, env: i686 }, { msystem: MINGW64, env: x86_64 }, { msystem: UCRT64, env: ucrt-x86_64 } ]
        include:
        - { sys: mingw32, env: i686 }
        - { sys: mingw64, env: x86_64 }
        - { sys: ucrt64,  env: ucrt-x86_64 }  # Experimental!
    name: ${{ matrix.sample }}-${{ matrix.sys }}
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      -
        name: Checkout cx_Freeze
        uses: actions/checkout@v2
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
      -
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.sys }}
          install: >-
            mingw-w64-${{ matrix.env }}-toolchain
            mingw-w64-${{ matrix.env }}-python-pip
            mingw-w64-${{ matrix.env }}-python-setuptools
            mingw-w64-${{ matrix.env }}-python-wheel
            mingw-w64-${{ matrix.env }}-python-importlib-metadata
            mingw-w64-${{ matrix.env }}-python-cx-logging
      -
        name: Build the package
        run: |
          #pip install . --no-deps -v
          makepkg-mingw -sCLfc --noconfirm --noprogressbar
          pacman --noconfirm -U mingw-w64-${{ matrix.env }}-*-any.pkg.tar.xz
      -
        name: Freeze and run "${{ matrix.sample }}"
        id: freeze-and-run
        run: ./ci/build-test-one.sh ${{ matrix.sample }} || echo "::set-output name=status::$?"
      -
        name: Collect images and logs
        run: |
          cd cx_Freeze/samples/${{ matrix.sample }}
          mv build/*/*.png . || true
          mv build/*/*.log . || true
      -
        name: Upload the snapshots and logs
        uses: actions/upload-artifact@v2
        with:
          name: screensnapshots
          path: |
            ./cx_Freeze/samples/${{ matrix.sample }}/*.png
            ./cx_Freeze/samples/${{ matrix.sample }}/*.log
          if-no-files-found: ignore
      -
        name: Status
        run: exit ${{ steps.freeze-and-run.outputs.status }}
