name: 7-Tests numpy+mkl (windows)

on:
  #push:
  #  branches: [ main ]
  workflow_dispatch:

jobs:
  test1:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        sample: [pandas]
        os: [windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
        architecture: [x64]
    runs-on: ${{ matrix.os }}
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: '1'
    steps:
      -
        name: Checkout cx_Freeze
        uses: actions/checkout@v2
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
      -
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      -
        name: Restore wheelhouse from cache
        uses: actions/cache@v2
        with:
          path: wheelhouse/*
          key: wheelhouse-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.architecture }}-${{ hashFiles('**/*.py', '**/*.c', '**/*.rst', '**/*.sh') }}
          restore-keys: wheelhouse-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.architecture }}-
      -
        run: python -m sysconfig
      -
        name: Freeze and run "${{ matrix.sample }}" (numpy+mkl)
        id: freeze-and-run
        run: |
          echo "::group::Install dependencies"
          pip install -f wheelhouse numpy pandas
          echo "::endgroup::"
          ./ci/build-test-one.sh ${{ matrix.sample }} || echo "::set-output name=status::$?"
      -
        name: Collect images and logs
        run: |
          cd cx_Freeze/samples/${{ matrix.sample }}
          mv build/*/*.png . || true
          mv build/*/*.log . || true
      -
        name: Upload the snapshots and logs
        uses: actions/upload-artifact@v2
        with:
          name: screensnapshots
          path: |
            ./cx_Freeze/samples/${{ matrix.sample }}/*.png
            ./cx_Freeze/samples/${{ matrix.sample }}/*.log
          if-no-files-found: ignore
      -
        name: Status
        run: exit ${{ steps.freeze-and-run.outputs.status }}
        shell: bash

  test2:
    name: Test in virtual environment
    strategy:
      fail-fast: false
      matrix:
        sample: [pandas]
        os: [windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
        architecture: [x64]
    runs-on: ${{ matrix.os }}
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: '1'
    steps:
      -
        name: Checkout cx_Freeze
        uses: actions/checkout@v2
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
      -
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      -
        name: Restore wheelhouse from cache
        uses: actions/cache@v2
        with:
          path: wheelhouse/*
          key: wheelhouse-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.architecture }}-${{ hashFiles('**/*.py', '**/*.c', '**/*.rst', '**/*.sh') }}
          restore-keys: wheelhouse-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.architecture }}-
      -
        name: Freeze and run "${{ matrix.sample }}" (numpy+mkl)
        run: |
          echo "::group::Create venv with dependencies"
          python -m venv venv
          source venv/scripts/activate
          pip install -f wheelhouse numpy pandas
          echo "::endgroup::"
          ./ci/build-test-one.sh ${{ matrix.sample }} || echo "::set-output name=status::$?"
        shell: bash
      -
        name: Collect images and logs
        run: |
          cd cx_Freeze/samples/${{ matrix.sample }}
          mv build/*/*.png . || true
          mv build/*/*.log . || true
      -
        name: Upload the snapshots and logs
        uses: actions/upload-artifact@v2
        with:
          name: screensnapshots
          path: |
            ./cx_Freeze/samples/${{ matrix.sample }}/*.png
            ./cx_Freeze/samples/${{ matrix.sample }}/*.log
          if-no-files-found: ignore
      #    path: ./cx_Freeze/samples/pandas/build/*/**
      -
        name: Status
        run: exit ${{ steps.freeze-and-run.outputs.status }}
        shell: bash
