name: Build wheel

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  macos_cibuildwheel:
    name: Build wheel using cibuildwheel on macOS
    strategy:
      matrix:
        platform: [x86_64]
    runs-on: macos-latest
    continue-on-error: true
    steps:
      -
        uses: actions/checkout@v2
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
      -
        uses: actions/setup-python@v2
      -
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel==2.3.1
      -
        name: Build the wheel
        env:
          CIBW_BUILD: cp3*-m*_x86_64
          #CIBW_SKIP: cp35*
          CIBW_BUILD_VERBOSITY: 1
          #CIBW_BEFORE_BUILD: python -m pip install --upgrade pip && pip install -U importlib-metadata setuptools wheel && python -m sysconfig
        run: |
          python -m cibuildwheel --output-dir wheelhouse .
      -
        name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: cx-freeze-wheelhouse
          path: wheelhouse
  linux:
    name: Build wheel using manylinux2010
    strategy:
      matrix:
        platform: [x86_64]
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      -
        uses: actions/checkout@v2
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
      - 
        uses: actions/setup-python@v2
      -
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel==2.3.1
      #-
      #  name: Load the docker image
      #  env:
      #    PLATFORM: ${{ matrix.platform }}
      #    IMAGE_NAME: manylinux2010_${{ matrix.platform }}
      #  run: docker load -i /tmp/docker/${IMAGE_NAME}.tar
      -
        name: Build the wheel
        env:
          CIBW_BUILD: cp3*-m*_x86_64
          #CIBW_SKIP: cp35*
          CIBW_BUILD_VERBOSITY: 1
          #CIBW_BEFORE_BUILD: python -m pip install --upgrade pip && pip install -U importlib-metadata setuptools wheel && python -m sysconfig
          #CIBW_MANYLINUX_X86_64_IMAGE: manylinux2010_${{ matrix.platform }}
        run: |
          python -m cibuildwheel --output-dir wheelhouse .
      - name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: cx-freeze-wheelhouse
          path: wheelhouse
  publish:
    needs: [macos_cibuildwheel, linux]
    runs-on: ubuntu-20.04
    name: "Publish"
    steps:
      - uses: actions/checkout@v2
        with:
          repository: marcelotduarte/cx_Freeze
          ref: develop
      -
        uses: actions/setup-python@v2
      -
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools
      - name: Download the artifact
        uses: actions/download-artifact@v2
        with:
          name: cx-freeze-wheelhouse
          path: wheelhouse
      - name: Build the docs
        run: |
          pip install .[doc]
          make -C doc
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: wheelhouse
      - name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: cx-freeze-wheelhouse
          path: wheelhouse
