name: CI-Conda

on:
  workflow_dispatch:
    inputs:
      branch:
        default: develop
        required: true
        type: choice
        options:
          - develop
          - main
      build_freeze_core:
        default: false
        required: false
        type: boolean

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build_conda:
    name: Build conda packages
    uses: ./.github/workflows/build-packages-conda.yml
    with:
      branch: ${{ inputs.branch }}
      build_freeze_core: ${{ inputs.build_freeze_core }}
    permissions:
      contents: read

  matrix:
    name: Generate matrix of tests
    runs-on: ubuntu-slim
    steps:
      - name: Extra includes
        id: includes
        run: |
          import json, os
          os_and_version = [
              {"os": "ubuntu", "os-version": "latest", "arch": "x86_64"},
              {"os": "windows", "os-version": "latest", "arch": "x86_64"},
              {"os": "macos", "os-version": "15-intel", "arch": "x86_64"},
              {"os": "ubuntu", "os-version": "24.04-arm", "arch": "arm64"},
              {"os": "windows", "os-version": "11-arm", "arch": "arm64"},
              {"os": "macos", "os-version": "15", "arch": "arm64"},
          ]
          python_version = ["3.11", "3.12", "3.13", "3.14", "3.14t", "3.15-dev", "3.15t-dev"]

          print("include = [")
          include = []
          for osver in os_and_version:
              for pyver in python_version:
                  line = osver.copy()
                  line["python-version"] = pyver
                  print(f"\t{line},")
                  include += [line]
          print("]")

          with open(os.environ["GITHUB_OUTPUT"], "a+") as f:
            print("data="+json.dumps({"include": include}), file=f)
        shell: python

    outputs:
      data: ${{ steps.includes.outputs.data }}

  tests:
    needs:
      - build_conda
      - matrix
    runs-on: ${{ matrix.os }}-${{ matrix.os-version }}
    strategy:
      matrix: ${{ fromJSON(needs.matrix.outputs.data) }}
      fail-fast: false
    defaults:
      run:
        shell: bash
    steps:

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install -qy alien

      - name: Fetch only the required files for testing
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          ref: ${{ inputs.branch }}
          repository: marcelotduarte/cx_Freeze
          sparse-checkout: |
            pyproject.toml
            ci
            samples
            tests

      - name: Download the wheels of freeze-core
        if: ${{ inputs.build_freeze_core }}
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          merge-multiple: true
          pattern: freeze-core-conda
          path: condahouse

      - name: Download the wheel of cx-freeze
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: cx-freeze-conda
          path: condahouse

      - name: List files
        run: find . -not -path '*/.*' -print

      - uses: conda-incubator/setup-miniconda@v4
        with:
          activate-environment: test-${{ matrix.os }}-${{ matrix.os-version }}
          python-version: ${{ matrix.python-version }}
          architecture: x64
          channels: conda-forge

      - name: Install dependencies to test
        run: |
          ci/install-tools.sh --tests
          conda install ./condahouse/noarch/cx_freeze-*-.conda --yes

      - name: Env
        run: env | sort

      - name: Sysconfig
        run: python -m sysconfig

      - name: platform
        run: python -m platform

      - name: platform machine
        run: python -c "import platform; print(platform.machine())"

      - name: Generate coverage report
        run: coverage run -m pytest --dist=loadfile --durations=20 -n4 -rpfEsXx tests

      - name: Upload coverage reports
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: cov-${{ matrix.python-version }}.${{ matrix.os }}-${{ strategy.job-index }}
          path: .coverage.*
          include-hidden-files: true
