name: CI

on:
  workflow_dispatch:
    inputs:
      branch:
        default: develop
        required: true
        type: choice
        options:
          - develop
          - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build_wheel:
    name: Build wheels
    uses: ./.github/workflows/build-wheel.yml
    with:
      branch: ${{ inputs.branch }}
    permissions:
      contents: read

  matrix:
    name: Generate matrix of tests
    runs-on: ubuntu-slim
    steps:
      - name: Extra includes
        id: includes
        run: |
          import json, os
          python_version = ["3.11", "3.12", "3.13", "3.14", "3.14t", "3.15-dev", "3.15t-dev"]
          include = [
              {
                  "os": "ubuntu",
                  "os-version": "latest",
                  "arch": "x86_64",
                  "python-version": python_version,
              },
              {
                  "os": "windows",
                  "os-version": "latest",
                  "arch": "x86_64",
                  "python-version": python_version,
              },
              {
                  "os": "macos",
                  "os-version": "15-intel",
                  "arch": "x86_64",
                  "python-version": python_version,
              },
              {
                  "os": "ubuntu",
                  "os-version": "24.04-arm",
                  "arch": "arm64",
                  "python-version": python_version,
              },
              {
                  "os": "windows",
                  "os-version": "11-arm",
                  "arch": "arm64",
                  "python-version": python_version,
              },
              {
                  "os": "macos",
                  "os-version": "15",
                  "arch": "arm64",
                  "python-version": python_version,
              },
            ]
          with open(os.environ["GITHUB_OUTPUT"], "a+") as f:
            print("data="+json.dumps({"include": include}), file=f)
          print("data="+json.dumps({"include": include}))
        shell: python

    outputs:
      data: ${{ steps.includes.outputs.data }}

  tests:
    needs:
      - build_wheel
      - matrix
    runs-on: ${{ matrix.os }}-${{ matrix.os-version }}
    strategy:
      matrix: ${{ fromJSON(needs.matrix.outputs.data) }}
      fail-fast: false
    defaults:
      run:
        shell: bash
    env:
      UV_NO_PROGRESS: true
    steps:
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install -qy alien

      - name: Fetch only the required files for testing
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          ref: ${{ inputs.branch }}
          repository: marcelotduarte/cx_Freeze
          sparse-checkout: |
            ci
            pyproject.toml
            samples
            tests

      - name: List files
        run: find . -name '*' -print

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python-version }}

      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          activate-environment: true
          cache-dependency-glob: "pyproject.toml"
          enable-cache: true

      - name: Env
        run: env | sort

      - name: Sysconfig
        run: uv run --no-project -m sysconfig

      - name: platform
        run: uv run --no-project -m platform

      - name: platform machine
        run: uv run --no-project python -c "import platform; print(platform.machine())"

      - name: Download the wheel
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          merge-multiple: true
          pattern: cx-freeze-wheel
          path: wheelhouse

      - name: Install the dependencies for the tests
        run: uv pip install --upgrade -r pyproject.toml --group tests

      - name: Install cx_Freeze from wheelhouse
        run: |
          uv pip install cx_Freeze -f wheelhouse \
              --no-build --no-deps --no-index --prerelease=allow --reinstall

      - name: Generate coverage report
        run: uv run --no-project coverage run

      - name: Upload coverage reports
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: cov-${{ matrix.python-version }}.${{ matrix.os }}-${{ strategy.job-index }}
          path: .coverage.*
          include-hidden-files: true
