name: Create manylinux2010

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04]
        platform: ["x86_64"]
    name: Build manylinux
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 4117e7c197a85a536ff90123e52c9c6f7d30780e
          repository: pypa/manylinux
      - name: Patch the build scripts
        env:
          SCRIPTS: docker/build_scripts
        run: |
          sed -i 's/xargs -0 rm -f/xargs -0 ls -l/g' $SCRIPTS/build.sh
          sed -i 's/2.7.18 3.5.10 //g' $SCRIPTS/build_env.sh
          sed -i 's/--disable-shared/--enable-shared LDFLAGS=\"-Wl,-rpath ${prefix}\/lib\"/g' $SCRIPTS/build_utils.sh
      - name: Build the docker
        env:
          PLATFORM: ${{ matrix.platform }}
        run: |
          docker build --rm -t "manylinux2010_$PLATFORM" -f "docker/Dockerfile-$PLATFORM" docker/
      - name: Save the docker
        env:
          PLATFORM: ${{ matrix.platform }}
        run: |
          docker save -o manylinux2010_${PLATFORM}.tar "manylinux2010_$PLATFORM"
      - name: Display structure of docker files
        run: ls -R
      - name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: manylinux2010_${{ matrix.platform }}
          path: ./*.tar
  linux:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-20.04]
    name: Build wheel using manylinux2010
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: macos
          repository: marcelotduarte/cx_Freeze
          submodules: true
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel==1.8.0
      - name: Download the manylinux docker
        uses: actions/download-artifact@v2
        with:
          name: manylinux2010_x86_64
          path: docker
      - name: Display structure of docker files
        run: ls -R
        working-directory: docker
      - name: Build the wheel
        env:
          CIBW_BUILD: cp3*-m*_x86_64
          CIBW_SKIP: cp35*
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BEFORE_BUILD: python -m pip install --upgrade pip && pip install -U importlib-metadata setuptools wheel && python -m sysconfig
          CIBW_MANYLINUX_X86_64_IMAGE: docker/manylinux2010_x86_64.tar
        run: |
          python -m cibuildwheel --output-dir wheelhouse .
      - name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: wheelhouse
          path: wheelhouse
