name: CI-pre-commit

on:
  workflow_dispatch:
    inputs:
      branch:
        default: develop
        required: true
        type: choice
        options:
          - develop
          - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  pre_commit:
    permissions:
      contents: write # Required for pre-commit-ci lite
      id-token: write # Required for pre-commit-ci lite
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
          ref: ${{ inputs.branch }}
          repository: marcelotduarte/cx_Freeze

      - uses: j178/prek-action@v2
        with:
          extra-args: "--all-files --skip=build-docs --skip=ty"

  type_check:
    name: Type check
    runs-on: ${{ matrix.os }}-${{ matrix.os_version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows, macos]
        os_version: [latest]
        python-version: ["3.11"]
    defaults:
      run:
        shell: bash
    env:
      UV_NO_PROGRESS: true
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
          ref: ${{ inputs.branch }}
          repository: marcelotduarte/cx_Freeze

      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          activate-environment: true
          cache-dependency-glob: "pyproject.toml"
          enable-cache: true

      - name: Install the dependencies for the tests
        run: uv pip install --upgrade -r pyproject.toml --group tests

      - name: Type check
        uses: j178/prek-action@v2
        with:
          extra-args: "--all-files ty"
