on:
  workflow_dispatch:
    inputs:
      branch:
        default: develop
        required: true
        type: choice
        options:
          - develop
      python-version:
        default: "3.9-3.13"
        required: false
        type: choice
        options:
          - "3.9-3.13"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
      deps:
        default: "p"
        required: false
        type: choice
        options:
          - "p"
          - "d"
          - "l"
      bdist:
        default: ""
        required: false
        type: choice
        options:
          - ""
          - "bdist_appimage"
          - "bdist_deb"
          - "bdist_rpm"

name: Test-3-conda (Linux)
jobs:
  tests:
    name: Test-conda-linux-${{ inputs.branch }}-${{ inputs.version }}-${{ inputs.bdist }}
    uses: ./.github/workflows/test-3-conda-base.yml
    with:
      branch: ${{ inputs.branch }}
      python-version: ${{ inputs.python-version }}
      deps: ${{ inputs.deps }}
      bdist: ${{ inputs.bdist }}
      os: ubuntu-latest
