on:
  workflow_dispatch:
    inputs:
      branch:
        default: develop
        required: true
        type: choice
        options:
          - develop
      python-version:
        default: "3.11,3.12,3.13,3.14"
        required: false
        type: choice
        options:
          - "3.11,3.12,3.13,3.14"
          - "3.14t,3.15-dev,3.15t-dev"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
          - "3.14t"
          - "3.15-dev"
          - "3.15t-dev"
      deps:
        default: "d"
        required: false
        type: choice
        options:
          - "d"
          - "e"
          - "p"
          - "l"
      bdist:
        default: ""
        required: false
        type: choice
        options:
          - ""
          - "bdist_mac"
          - "bdist_dmg"
      os_version:
        default: "15"
        required: false
        type: choice
        options:
          - "14"
          - "15"
          - "26"
          - "15-intel"
          - "26-intel"

name: Test-1-pip (macOS)
jobs:
  tests:
    name: Test-pip-macos-${{ inputs.branch }}-${{ inputs.deps }}-${{ inputs.bdist }}
    uses: ./.github/workflows/test-1-pip-base.yml
    with:
      branch: ${{ inputs.branch }}
      python-version: ${{ inputs.python-version }}
      deps: ${{ inputs.deps }}
      bdist: ${{ inputs.bdist }}
      os: macos
      os_version: ${{ inputs.os_version }}
