name: Test-3-miniconda (windows)

on:
  #push:
  #  branches: [ main ]
  workflow_dispatch:

jobs:
  matrix:
    name: Generate matrix of samples
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      -
        uses: actions/checkout@v2
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
      -
        uses: actions/setup-python@v2
      -
        id: set-matrix
        run: |
          import json
          with open("ci/build-test.json") as fp:
              data = json.load(fp)
          samples = json.dumps(list(data.keys()))
          print(f"::set-output name=matrix::{samples}")
        shell: python

  tests:
    needs: [matrix]
    strategy:
      fail-fast: false
      matrix:
        sample: ${{ fromJSON(needs.matrix.outputs.matrix) }}
        os: [windows-latest]
        #python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
        python-version: ["3.9"]
        architecture: [x64]
    name: ${{ matrix.sample }}-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.architecture }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    env:
      OS_PY_ARCH: ${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.architecture }}
      PIP_DISABLE_PIP_VERSION_CHECK: '1'
    steps:
      -
        name: Checkout cx_Freeze
        uses: actions/checkout@v2
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
      -
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: freeze-${{ env.OS_PY_ARCH }}
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
          channels: conda-forge
      -
        name: Set variable BASE_PLATFORM
        run: |
          import sysconfig
          platform = sysconfig.get_platform()
          python_version = sysconfig.get_python_version()
          print(f"::set-output name=BASE_PLATFORM::{platform}-{python_version}")
        shell: python
        id: vars
      -
        uses: actions/cache@v2
        with:
          key: wheelhouse-${{ steps.vars.outputs.BASE_PLATFORM }}-${{ github.sha }}
          path: ${{ steps.conda.outputs.CONDA_BLD }}/*/*.tar.bz2
      -
        name: Freeze and run "${{ matrix.sample }}"
        id: freeze-and-run
        run: |
          ls -l
          ls -l win-64
          echo "::group::conda info"
          conda info
          echo "::endgroup::"
          echo "::group::cx_Logging"
          pip install -U cx_Logging
          echo "::endgroup::"
          ./ci/build-test-one.sh ${{ matrix.sample }} || echo "::set-output name=status::$?"
      -
        name: Collect images and logs
        run: |
          cd cx_Freeze/samples/${{ matrix.sample }}
          mv build/*/*.png . || true
          mv build/*/*.log . || true
      -
        name: Upload the snapshots and logs
        uses: actions/upload-artifact@v2
        with:
          name: screensnapshots
          path: |
            ./cx_Freeze/samples/${{ matrix.sample }}/*.png
            ./cx_Freeze/samples/${{ matrix.sample }}/*.log
          if-no-files-found: ignore
      -
        name: Status
        run: exit ${{ steps.freeze-and-run.outputs.status }}
