name: Test-4-cxfreeze script

on:
  #push:
  #  branches: [ main ]
  workflow_dispatch:

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        architecture: [x64, x86]
        exclude:
          - os: ubuntu-latest
            architecture: x86
          - os: macos-latest
            architecture: x86
    name: cxfreeze-${{ matrix.os }}-${{ matrix.architecture }}-${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:

      - name: Checkout cx_Freeze
        uses: actions/checkout@v4
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze

      - uses: actions/setup-python@v5
        with:
          cache: 'pip'
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --pre cx_Freeze

      - run: python -m sysconfig

      - run: cxfreeze --version

      - name: Freeze simple sample (2-different target-name)
        working-directory: samples/simple
        run: |
          cxfreeze hello.py --silent --target-name Hello-0.1 --target-dir build --excludes tkinter
          ls -l
          ls -l build

      - name: Run simple sample (2-different target-name)
        working-directory: samples/simple/build
        run: ./Hello-0.1
