name: Test-1-wheels using pipenv

on:
  #push:
  #  branches: [ main ]
  workflow_dispatch:

jobs:
  matrix:
    name: Generate matrix of samples
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      -
        uses: actions/checkout@v3
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
      -
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      -
        run: |
          import json
          with open("ci/build-test.json") as fp:
              data = json.load(fp)
          with open("ci/build-test.data", "w+") as out:
              out.write(json.dumps(list(data.keys())))
        shell: python
      -
        id: set-matrix
        run: echo "matrix=$(cat ci/build-test.data)" >> $GITHUB_OUTPUT

  tests:
    needs: [matrix]
    strategy:
      fail-fast: false
      matrix:
        sample: ${{ fromJSON(needs.matrix.outputs.matrix) }}
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10"]
        architecture: [x64]
        exclude:
          - os: ubuntu-latest
            sample: pythonnet-demo
          - os: macos-latest
            sample: pythonnet-demo
          - os: ubuntu-latest
            sample: service
          - os: ubuntu-latest
            sample: service-asyncio
          - os: macos-latest
            sample: service
          - os: macos-latest
            sample: service-asyncio
          #- sample: pandas
          #  python-version: "3.10"
        branch: [develop]
    name: ${{ matrix.sample }}-${{ matrix.os }}-${{ matrix.architecture }}-${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    steps:
      -
        name: Checkout cx_Freeze
        uses: actions/checkout@v3
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
      -
        name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      -
        name: Freeze and run "${{ matrix.sample }}"
        id: freeze-and-run
        env:
          QT_DEBUG_PLUGINS: 1
        run: ./ci/build-test-one.sh ${{ matrix.sample }} --pipenv || (echo "status=$?" >> $GITHUB_OUTPUT)
        shell: bash
      -
        name: Collect images and logs
        working-directory: samples/${{ matrix.sample }}
        run: mv build/*/*.{err,log,png} . || true
        shell: bash
      -
        name: Upload the snapshots and logs
        uses: actions/upload-artifact@v3
        with:
          name: screensnapshots
          path: |
            ./samples/${{ matrix.sample }}/*.err
            ./samples/${{ matrix.sample }}/*.log
            ./samples/${{ matrix.sample }}/*.png
          if-no-files-found: ignore
      -
        name: Return sucess or error code
        run: |
          if [ "${{ steps.freeze-and-run.outputs.status }}" == "" ] ; then
            exit -1
          else
            exit ${{ steps.freeze-and-run.outputs.status }}
          fi
        shell: bash
