name: Test-1-wheels (macOS/bdist_mac)

on:
  #push:
  #  branches: [ main ]
  workflow_dispatch:

jobs:
  matrix:
    name: Generate matrix of samples
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      -
        uses: actions/checkout@v3
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
      -
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      -
        id: set-matrix
        run: echo "matrix=$(python ci/_platform.py macos)" >> $GITHUB_OUTPUT

  tests:
    needs: [matrix]
    strategy:
      fail-fast: false
      matrix:
        sample: ${{ fromJSON(needs.matrix.outputs.matrix) }}
        os: [macos-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        architecture: [x64]
        branch: [develop]
    name: ${{ matrix.sample }}-${{ matrix.os }}-${{ matrix.architecture }}-${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    steps:
      -
        name: Checkout cx_Freeze
        uses: actions/checkout@v3
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
      -
        name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      -
        name: Freeze and run "${{ matrix.sample }}"
        id: freeze-and-run
        env:
          TEST_BDIST_MAC: 1
        run: |
          ./ci/build-test-one.sh ${{ matrix.sample }} --debug
          echo "status=$?" >> $GITHUB_OUTPUT
        continue-on-error: true
      -
        name: Collect images and logs
        working-directory: samples/${{ matrix.sample }}
        run: mv build/*/*.{err,log,png} . || true
      -
        name: Upload the snapshots and logs
        uses: actions/upload-artifact@v3
        with:
          name: screensnapshots
          path: |
            ./samples/${{ matrix.sample }}/*.err
            ./samples/${{ matrix.sample }}/*.log
            ./samples/${{ matrix.sample }}/*.png
          if-no-files-found: ignore
      -
        name: Return sucess or error code
        run: |
          if [ "${{ steps.freeze-and-run.outputs.status }}" == "" ] ; then
            exit -1
          else
            exit ${{ steps.freeze-and-run.outputs.status }}
          fi
        shell: bash
