on:
  workflow_dispatch:
    inputs:
      branch:
        default: develop
        required: true
        type: choice
        options:
          - develop
          - develop615x
      version:
        default: ""
        required: false
        type: choice
        options:
          - ""
          - "d"
          - "e"
          - "l"
      bdist:
        default: ""
        required: false
        type: choice
        options:
          - ""
          - "bdist_mac"
          - "bdist_dmg"

name: Test-3-conda (macOS)
jobs:
  tests:
    name: Test-conda-macos-${{ inputs.branch }}-${{ inputs.version }}-${{ inputs.bdist }}
    uses: ./.github/workflows/test-3-conda-base.yml
    with:
      branch: ${{ inputs.branch }}
      version: ${{ inputs.version }}
      bdist: ${{ inputs.bdist }}
      os: macos-latest
