name: Test-5-wheels using 3.13-dev

on:
  workflow_dispatch:

jobs:
  matrix:
    name: Generate matrix of samples
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:

      - uses: actions/checkout@v5
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze

      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - id: set-matrix
        run: echo "matrix=$(python ci/_platform.py windows)" >> $GITHUB_OUTPUT

  tests:
    needs: [matrix]
    strategy:
      fail-fast: false
      matrix:
        sample: ${{ fromJSON(needs.matrix.outputs.matrix) }}
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.13-dev"]
        architecture: [x64, x86]
        branch: [develop]
        exclude:
          - os: ubuntu-latest
            architecture: x86
          - os: macos-latest
            architecture: x86
          - os: ubuntu-latest
            sample: pythonnet-demo
          - os: windows-latest
            sample: pythonnet-demo
          - os: macos-latest
            sample: pythonnet-demo
          - os: ubuntu-latest
            sample: service
          - os: macos-latest
            sample: service
          - os: ubuntu-latest
            sample: service-asyncio
          - os: macos-latest
            sample: service-asyncio
          - os: ubuntu-latest
            sample: matplotlib
          - sample: pyside2
          - sample: pyside2-simplebrowser
          - sample: pyqt6
          - sample: pyqt6-simplebrowser
          - sample: pyside6
          - sample: pyside6-simplebrowser
    name: ${{ matrix.sample }}-${{ matrix.os }}-${{ matrix.architecture }}-${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:

      - name: Checkout cx_Freeze
        uses: actions/checkout@v5
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
          allow-prereleases: true

      - name: Freeze and run "${{ matrix.sample }}"
        env:
          TEST_BDIST: bdist_mac
        id: freeze-and-run
        run: |
          export PIP_PRE=true
          export PIP_ONLY_BINARY=lief,numpy,pandas,PySide2,PySide6,PyQt5,PyQt6
          ./ci/build-test-one.sh ${{ matrix.sample }} --debug --venv

      - name: Collect images and logs
        if: ${{ always() }}
        working-directory: samples/${{ matrix.sample }}
        run: |
          mkdir ${{ matrix.sample }}-${{ matrix.os }}
          cp build/exe.*/*.{err,log,png} ${{ matrix.sample }}-${{ matrix.os }} || true
          mkdir ${{ matrix.sample }}-${{ matrix.os }}/app-${{ matrix.python-version }}
          cp build/*.app/Contents/MacOS/*.{err,log,png} ${{ matrix.sample }}-${{ matrix.os }}/app-${{ matrix.python-version }} || true

      - name: Upload the snapshots and logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v5
        with:
          name: screensnapshots
          path: ./samples/${{ matrix.sample }}/${{ matrix.sample }}-${{ matrix.os }}/**
          if-no-files-found: ignore
