name: Test-5-qtweb-macos

on:
  #push:
  #  branches: [ main ]
  workflow_dispatch:

jobs:
  tests:
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        python-version: [3.8]
        architecture: [x64]
    runs-on: ${{ matrix.os }}
    steps:
      -
        name: Checkout cx_Freeze
        uses: actions/checkout@v3
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
      -
        name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      -
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade importlib-metadata setuptools wheel
          pip install --upgrade PyQtWebEngine
          pip install --no-index -f wheelhouse cx-freeze --no-deps
      -
        run: python -m sysconfig
      -
        run: cxfreeze --version
      -
        uses: actions/upload-artifact@v2
        with:
          name: site-packages-PyQt5-${{ matrix.python-version }}
          path: /Users/runner/hostedtoolcache/Python/3.8.8/x64/lib/python3.8/site-packages/PyQt5/**
      -
        name: Freeze pyqt5-webengine sample
        working-directory: cx_Freeze/samples/pyqt5-webengine
        run: |
          python setup.py build_exe --silent
          python setup.py bdist_mac
      -
        name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: frozen-pyqtweb-${{ matrix.python-version }}
          path: ./cx_Freeze/samples/pyqt5-webengine/build/**
      -
        name: Run pyqt5-webengine sample app
        working-directory: cx_Freeze/samples/pyqt5-webengine/build
        run: ./PyQt5WebengineTest.app/Contents/MacOS/test_pyqt5_webengine ; echo $?
