on:
  workflow_dispatch:
    inputs:
      branch:
        default: develop
        required: true
        type: choice
        options:
          - develop
          - develop615x
      version:
        default: ""
        required: false
        type: choice
        options:
          - ""
          - "d"
          - "e"
          - "l"
      bdist:
        default: ""
        required: false
        type: choice
        options:
          - ""
          - "bdist_msi"

name: Test-1-wheels (Windows)
jobs:
  tests:
    name: Test-wheels-macos-${{ inputs.branch }}-${{ inputs.version }}-${{ inputs.bdist }}
    uses: ./.github/workflows/test-1-pip-base.yml
    with:
      branch: ${{ inputs.branch }}
      version: ${{ inputs.version }}
      bdist: ${{ inputs.bdist }}
      os: windows-latest
