name: Test-3-conda (macOS)

on:
  #push:
  #  branches: [ main ]
  workflow_dispatch:

jobs:
  matrix:
    name: Generate matrix of samples
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:

      - uses: actions/checkout@v4
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - id: set-matrix
        run: echo "matrix=$(python ci/_platform.py macos)" >> $GITHUB_OUTPUT

  tests:
    needs: [matrix]
    strategy:
      fail-fast: false
      matrix:
        sample: ${{ fromJSON(needs.matrix.outputs.matrix) }}
        os: [macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        architecture: [x64]
        exclude:
          - sample: pyqt6
          - sample: pyqt6-simplebrowser
          - sample: pyside6-simplebrowser
          - sample: matplotlib_tk
            python-version: "3.8"
    name: ${{ matrix.sample }}-${{ matrix.os }}-${{ matrix.architecture }}-${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    env:
      KEY_BASE: ${{ matrix.os }}-${{ matrix.architecture }}-${{ matrix.python-version }}
      PIP_DISABLE_PIP_VERSION_CHECK: '1'
    steps:

      - name: Checkout cx_Freeze
        uses: actions/checkout@v4
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: freeze-${{ env.KEY_BASE }}
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
          channels: conda-forge

      - name: Freeze and run "${{ matrix.sample }}"
        env:
          TEST_BDIST: bdist_mac
        id: freeze-and-run
        run: ./ci/build-test-one.sh ${{ matrix.sample }} --debug

      - name: Collect images and logs
        if: ${{ always() }}
        working-directory: samples/${{ matrix.sample }}
        run: |
          mkdir ${{ matrix.sample }}-${{ matrix.os }}
          cp build/exe.*/*.{err,log,png} ${{ matrix.sample }}-${{ matrix.os }} || true
          mkdir ${{ matrix.sample }}-${{ matrix.os }}/app-${{ matrix.python-version }}
          cp build/*.app/Contents/MacOS/*.{err,log,png} ${{ matrix.sample }}-${{ matrix.os }}/app-${{ matrix.python-version }} || true

      - name: Upload the snapshots and logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: screensnapshots
          path: ./samples/${{ matrix.sample }}/${{ matrix.sample }}-${{ matrix.os }}/**
          if-no-files-found: ignore
