name: 2.1-Test on Windows

on:
  #push:
  #  branches: [ main ]
  workflow_dispatch:

jobs:
  tests:
    name: Test

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    runs-on: ${{ matrix.os }}

    steps:
      -
        name: Checkout cx_Freeze
        uses: actions/checkout@v2
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
      -
        name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      -
        name: Restore wheelhouse from cache
        uses: actions/cache@v2
        with:
          path: wheelhouse/*
          key: wheelhouse-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.architecture }}
      -
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U importlib-metadata setuptools wheel cx_Logging
      -
        name: Install cx-freeze
        run: pip install . -v
      -
        run: python -m sysconfig
      -
        run: cxfreeze --version
      -
        name: Freeze simple sample (2-different target-name)
        working-directory: cx_Freeze/samples/simple
        run: |
          cxfreeze --version
          cxfreeze hello.py --silent --target-name Hello-0.1 --target-dir build/one.win-amd64-${{ matrix.python-version }}
      -
        name: Run simple sample (2-different target-name)
        working-directory: cx_Freeze/samples/simple/build/one.win-amd64-${{ matrix.python-version }}
        run: ./Hello-0.1.exe
      -
        name: Freeze pandas sample (numpy+mkl)
        if: ${{ matrix.python-version == '3.8' }}
        working-directory: cx_Freeze/samples/pandas
        run: |
          curl https://download.lfd.uci.edu/pythonlibs/w4tscw6k/numpy-1.19.5+mkl-cp38-cp38-win_amd64.whl -o numpy-1.19.5+mkl-cp38-cp38-win_amd64.whl
          pip install --no-index numpy-1.19.5+mkl-cp38-cp38-win_amd64.whl
          python setup.py build_exe --silent
        shell: bash
      -
        name: Upload the artifact
        if: ${{ matrix.python-version == '3.8' }}
        uses: actions/upload-artifact@v2
        with:
          name: frozen-pandas
          path: ./cx_Freeze/samples/pandas/build/*/**
      -
        name: Run pandas sample (numpy+mkl)
        if: ${{ matrix.python-version == '3.8' }}
        working-directory: cx_Freeze/samples/pandas
        run: |
          ./build/exe.win-amd64-${{ matrix.python-version }}/test_pandas.exe
