name: Test-Windows

on:
  #push:
  #  branches: [ master ]
  workflow_dispatch:

jobs:
  tests:
    name: Test

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout cx_Freeze
      uses: actions/checkout@v2
      with:
        repository: marcelotduarte/cx_Freeze
        ref: develop
        path: cx_Freeze
    - name: Checkout cx_Logging
      uses: actions/checkout@v2
      with:
        repository: anthony-tuininga/cx_Logging
        path: cx_Logging
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel
    - name: Install cx-logging
      run: |
        cd cx_Logging
        python setup.py install
    - name: Install cx-freeze
      run: |
        cd cx_Freeze
        pip install .

    - name: Freeze cryptography sample
      working-directory: cx_Freeze/cx_Freeze/samples/cryptography
      run: |
        pip install cryptography
        python setup.py build_exe
    - name: Run cryptography sample
      working-directory: cx_Freeze/cx_Freeze/samples/cryptography
      run: ./build/exe.win-amd64-${{ matrix.python-version }}/test_crypt.exe

    - name: Freeze icon sample
      working-directory: cx_Freeze/cx_Freeze/samples/icon
      run: python setup.py build_exe --silent
    - name: Run icon sample
      working-directory: cx_Freeze/cx_Freeze/samples/icon
      run: |
        ./build/exe.win-amd64-${{ matrix.python-version }}/test_1.exe
        ./build/exe.win-amd64-${{ matrix.python-version }}/test_2.exe ação ótica côncavo peña

    - name: Freeze matplolib sample
      working-directory: cx_Freeze/cx_Freeze/samples/matplotlib
      run: |
        pip install matplotlib
        pip install wxPython
        python setup.py build_exe --silent
    - name: Run matplolib sample
      working-directory: cx_Freeze/cx_Freeze/samples/matplotlib
      run: |
        ./build/exe.win-amd64-${{ matrix.python-version }}/matplotlib_afm.exe
    
    - name: Freeze pandas sample
      working-directory: cx_Freeze/cx_Freeze/samples/pandas
      run: |
        pip install pandas
        python setup.py build_exe --silent
    - name: Run pandas sample
      working-directory: cx_Freeze/cx_Freeze/samples/pandas
      run: |
        ./build/exe.win-amd64-${{ matrix.python-version }}/test_pandas.exe
    
    - name: Freeze pillow sample
      working-directory: cx_Freeze/cx_Freeze/samples/pillow
      run: |
        pip install pillow
        python setup.py build_exe --silent
    - name: Run pillow sample
      working-directory: cx_Freeze/cx_Freeze/samples/pillow
      run: ./build/exe.win-amd64-${{ matrix.python-version }}/test_pillow.exe
    
    - name: Freeze pyside2 sample
      working-directory: cx_Freeze/cx_Freeze/samples/pyside2
      run: |
        pip install pyside2
        python setup.py build_exe --silent
    - name: Run pyside2 sample
      working-directory: cx_Freeze/cx_Freeze/samples/pyside2
      run: ./build/exe.win-amd64-${{ matrix.python-version }}/PySide2app.exe
    
    - name: Freeze service sample
      working-directory: cx_Freeze/cx_Freeze/samples/service
      run: |
        python setup.py build_exe --silent
    - name: Run service sample
      working-directory: cx_Freeze/cx_Freeze/samples/service
      run: ./build/exe.win-amd64-${{ matrix.python-version }}/cx_FreezeSampleService.exe --install sample

    - name: Freeze simple sample
      working-directory: cx_Freeze/cx_Freeze/samples/simple
      run: python setup.py build_exe --silent
    - name: Run simple sample
      working-directory: cx_Freeze/cx_Freeze/samples/simple
      run: ./build/exe.win-amd64-${{ matrix.python-version }}/hello.exe
    - name: Run simple sample (1-rename the executable)
      working-directory: cx_Freeze/cx_Freeze/samples/simple/build/exe.win-amd64-${{ matrix.python-version }}
      run: |
        mv hello.exe Test_Hello.exe
        ./Test_Hello.exe

    #- name: Freeze simple sample (2-different target-name)
    #  working-directory: cx_Freeze/cx_Freeze/samples/simple
    #  run: cxfreeze hello.py --silent --target-name Hello-0.1 --target-dir build/exe.win-amd64-${{ matrix.python-version }}.one
    #- name: Run simple sample (2-different target-name)
    #  working-directory: cx_Freeze/cx_Freeze/samples/simple/build/exe.win-amd64-${{ matrix.python-version }}.one
    #  run: ./Hello-0.1.exe
