name: Test-Windows-pipenv

on:
  #push:
  #  branches: [ master ]
  workflow_dispatch:

jobs:
  tests:
    name: Test

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout cx_Freeze
      uses: actions/checkout@v2
      with:
        repository: marcelotduarte/cx_Freeze
        ref: develop
        path: cx_Freeze
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel
    - name: Install cx-freeze
      working-directory: cx_Freeze
      run: pip install .
    - name: Install pipenv
      run: pip install pipenv
    - name: Install cx-logging
      if: ${{ matrix.python-version == '3.6' || matrix.python-version == '3.7' }}
      run: pip install cx_Logging
    - name: Install cx-logging
      if: ${{ matrix.python-version == '3.8' || matrix.python-version == '3.9' }}
      working-directory: cx_Freeze/cx_Logging
      run: |
        git submodule init
        git submodule update
        pip install .

    - name: Freeze cryptography sample
      working-directory: cx_Freeze/cx_Freeze/samples/cryptography
      run: |
        pipenv --python ${{ matrix.python-version }} --site-packages
        pipenv install cryptography
        pipenv run python setup.py build_exe --silent
    - name: Run cryptography sample
      working-directory: cx_Freeze/cx_Freeze/samples/cryptography
      run: ./build/exe.win-amd64-${{ matrix.python-version }}/test_crypt.exe

    - name: Freeze matplolib sample
      working-directory: cx_Freeze/cx_Freeze/samples/matplotlib
      run: |
        pipenv --python ${{ matrix.python-version }} --site-packages
        pipenv install matplotlib
        pipenv install wxPython
        pipenv run python setup.py build_exe --silent
    - name: Run matplolib sample
      working-directory: cx_Freeze/cx_Freeze/samples/matplotlib
      run: ./build/exe.win-amd64-${{ matrix.python-version }}/matplotlib_afm.exe

    - name: Freeze pandas sample
      working-directory: cx_Freeze/cx_Freeze/samples/pandas
      run: |
        pipenv --python ${{ matrix.python-version }} --site-packages
        pipenv install pandas
        pipenv run python setup.py build_exe --silent
    - name: Run pandas sample
      working-directory: cx_Freeze/cx_Freeze/samples/pandas
      run: ./build/exe.win-amd64-${{ matrix.python-version }}/test_pandas.exe

    - name: Freeze pillow sample
      working-directory: cx_Freeze/cx_Freeze/samples/pillow
      run: |
        pipenv --python ${{ matrix.python-version }} --site-packages
        pipenv install pillow
        pipenv run python setup.py build_exe --silent
    - name: Run pillow sample
      working-directory: cx_Freeze/cx_Freeze/samples/pillow
      run: ./build/exe.win-amd64-${{ matrix.python-version }}/test_pillow.exe

    - name: Freeze PyQt5 sample
      working-directory: cx_Freeze/cx_Freeze/samples/PyQt5
      run: |
        pipenv --python ${{ matrix.python-version }} --site-packages
        pipenv install PyQt5
        pipenv run python setup.py build_exe --silent
    - name: Run PyQt5 sample
      working-directory: cx_Freeze/cx_Freeze/samples/PyQt5
      run: ./build/exe.win-amd64-${{ matrix.python-version }}/PyQt5app.exe

    - name: Freeze PySide2 sample
      working-directory: cx_Freeze/cx_Freeze/samples/pyside2
      run: |
        pipenv --python ${{ matrix.python-version }} --site-packages
        pipenv install PySide2
        pipenv run python setup.py build_exe --silent
    - name: Run pyside2 sample
      working-directory: cx_Freeze/cx_Freeze/samples/pyside2
      run: ./build/exe.win-amd64-${{ matrix.python-version }}/PySide2app.exe

    - name: Freeze service sample
      working-directory: cx_Freeze/cx_Freeze/samples/service
      run: |
        pipenv --python ${{ matrix.python-version }} --site-packages
        pipenv run python setup.py build_exe --silent
    - name: Run service sample
      working-directory: cx_Freeze/cx_Freeze/samples/service/build/exe.win-amd64-${{ matrix.python-version }}
      run: ./cx_FreezeSampleService.exe --install sample
