name: 2.1-Complementary tests on Windows

on:
  #push:
  #  branches: [ main ]
  workflow_dispatch:

jobs:
  tests:
    name: Test

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: [3.8, 3.9]
        architecture: [x64]

    runs-on: ${{ matrix.os }}

    steps:
      -
        name: Checkout cx_Freeze
        uses: actions/checkout@v2
        with:
          ref: develop
          repository: marcelotduarte/cx_Freeze
      -
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      -
        name: Restore wheelhouse from cache
        uses: actions/cache@v2
        with:
          path: wheelhouse/*
          key: wheelhouse-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.architecture }}
      -
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U importlib-metadata setuptools wheel cx_Logging
          pip install --no-index -f wheelhouse cx-freeze
      -
        run: python -m sysconfig
      -
        run: cxfreeze --version
      -
        name: Freeze simple sample (2-different target-name)
        working-directory: cx_Freeze/samples/simple
        run: cxfreeze hello.py --silent --target-name Hello-0.1 --target-dir build/one.win-amd64-${{ matrix.python-version }}
      -
        name: Run simple sample (2-different target-name)
        working-directory: cx_Freeze/samples/simple/build/one.win-amd64-${{ matrix.python-version }}
        run: ./Hello-0.1.exe
      -
        name: Freeze service
        working-directory: cx_Freeze/samples/service
        run: python setup.py build_exe --silent
      -
        name: Run service sample
        working-directory: cx_Freeze/samples/service/build/exe.win-amd64-${{ matrix.python-version }}
        run: ./cx_FreezeSampleService.exe --install sample
      -
        name: Install numpy+mkl and pandas
        run: |
          if [ "${{ matrix.python-version }}" == "3.8" ] ; then
              curl https://download.lfd.uci.edu/pythonlibs/w4tscw6k/numpy-1.19.5+mkl-cp38-cp38-win_amd64.whl -o wheelhouse/numpy-1.19.5+mkl-cp38-cp38-win_amd64.whl
          else
              curl https://download.lfd.uci.edu/pythonlibs/w4tscw6k/numpy-1.20.2+mkl-cp39-cp39-win_amd64.whl -o wheelhouse/numpy-1.20.2+mkl-cp39-cp39-win_amd64.whl
          fi
          pip install --no-index -f wheelhouse numpy
          pip install pandas
        shell: bash
      -
        name: Freeze pandas sample (numpy+mkl)
        working-directory: cx_Freeze/samples/pandas
        run: python setup.py build_exe --silent
      -
        name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: frozen-pandas-${{ matrix.python-version }}
          path: ./cx_Freeze/samples/pandas/build/*/**
      -
        name: Run pandas sample (numpy+mkl)
        working-directory: cx_Freeze/samples/pandas/build
        run: ./exe.win-amd64-${{ matrix.python-version }}/test_pandas.exe
